# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Michael R. Lawrence <mike@michaellawrenceit.com>, 2014
# Michael R. Lawrence <mike@michaellawrenceit.com>, 2014
# Michael R. Lawrence <mike@michaellawrenceit.com>, 2014-2015
# Tanaka Yumi <yumi.tanaka@cybertrust.co.jp>, 2018
# tinaxd, 2018
msgid ""
msgstr ""
"Project-Id-Version: Sabayon Entropy Client\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-09-23 15:38+0200\n"
"PO-Revision-Date: 2018-09-23 13:38+0000\n"
"Last-Translator: lxnay <lxnay@sabayon.org>\n"
"Language-Team: Japanese (http://www.transifex.com/lxnay/sabayon-entropy/language/ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../lib/entropy/db/skel.py:518
#: ../../lib/entropy/client/interfaces/package/actions/action.py:100
#: ../../lib/entropy/locks.py:305
msgid "Acquiring shared lock on"
msgstr "上の共有ロックを取得"

#: ../../lib/entropy/db/skel.py:529
#: ../../lib/entropy/client/interfaces/package/actions/action.py:115
msgid "Acquired shared lock on"
msgstr "取得した共有ロック"

#: ../../lib/entropy/db/skel.py:563
#: ../../lib/entropy/client/interfaces/package/actions/action.py:98
#: ../../lib/entropy/locks.py:309
msgid "Acquiring exclusive lock on"
msgstr "排他ロックを取得"

#: ../../lib/entropy/db/skel.py:574
#: ../../lib/entropy/client/interfaces/package/actions/action.py:113
msgid "Acquired exclusive lock on"
msgstr "取得した排他的ロック"

#: ../../lib/entropy/db/skel.py:2537
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:988
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:1014
msgid "SPM"
msgstr "SPM（ソースパッケージマネージャ） "

#: ../../lib/entropy/db/skel.py:2538
msgid "Running packages metadata update"
msgstr "実行中のパッケージメタデータの更新"

#: ../../lib/entropy/db/skel.py:2539
msgid "it could take a while"
msgstr "それはしばらく時間がかかる可能性があり"

#: ../../lib/entropy/db/skel.py:2558 ../../lib/entropy/db/skel.py:2583
#: ../../lib/entropy/db/skel.py:2594
msgid "Entropy"
msgstr "エントロピー"

#: ../../lib/entropy/db/skel.py:2559
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:989
msgid "action"
msgstr "アクション"

#: ../../lib/entropy/db/skel.py:2584
msgid "package move actions complete"
msgstr "パッケージの移動アクションを完了し"

#: ../../lib/entropy/db/skel.py:2595
msgid "package moves completed successfully"
msgstr "パッケージの移動が正常に完了し"

#: ../../lib/entropy/db/skel.py:4604
msgid "Syncing current database"
msgstr "現在のデータベースの同期"

#: ../../lib/entropy/db/skel.py:4605
#: ../../lib/entropy/client/interfaces/db.py:311
msgid "please wait"
msgstr "お待ちください"

#: ../../lib/entropy/db/skel.py:4620
msgid "Removing entry"
msgstr "エントリを削除する"

#: ../../lib/entropy/db/skel.py:4639
msgid "Adding entry"
msgstr "エントリを追加する"

#: ../../lib/entropy/db/sqlite.py:2076
msgid "Exporting database table"
msgstr "データベーステーブルのエクスポート。"

#: ../../lib/entropy/db/sqlite.py:2116
msgid "Database Export complete."
msgstr "データベース·エクスポート·完全。"

#: ../../lib/entropy/db/sqlite.py:2525 ../../lib/entropy/db/sqlite.py:2629
#: ../../lib/entropy/db/sqlite.py:2737 ../../lib/entropy/db/sqlite.py:2750
#: ../../lib/entropy/db/sql.py:5491 ../../lib/entropy/db/sql.py:5504
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2721
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2858
#: ../../lib/entropy/client/interfaces/client.py:370
msgid "ATTENTION"
msgstr "注目"

#: ../../lib/entropy/db/sqlite.py:2527 ../../lib/entropy/db/sqlite.py:2631
msgid "updating repository metadata layout, please wait!"
msgstr "リポジトリ·メタデータのレイアウトを更新しています。しばらくお待ちください！"

#: ../../lib/entropy/db/sqlite.py:2738
msgid "generating provided_libs metadata, please wait!"
msgstr "提供されるライブラリのメタデータを生成しています。しばらくお待ちください！"

#: ../../lib/entropy/db/sql.py:5492
msgid "Spm error occurred"
msgstr "SPM：ソースパッケージマネージャでエラーが発生しました"

#: ../../lib/entropy/db/sql.py:5505
msgid "Spm Unique Identifier not found for"
msgstr "SPM（ソースパッケージマネージャ）一意識別子が見つかりません"

#: ../../lib/entropy/core/settings/base.py:2102
msgid "No description"
msgstr "記載なし"

#: ../../lib/kswitch/__init__.py:122
msgid "has been installed."
msgstr "インストールされている。"

#: ../../lib/kswitch/__init__.py:123 ../../lib/kswitch/__init__.py:199
#: ../../lib/kswitch/__init__.py:217
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3514
#: ../../lib/entropy/client/interfaces/db.py:456
#: ../../lib/entropy/client/interfaces/db.py:647
#: ../../lib/entropy/client/interfaces/db.py:2037
#: ../../lib/entropy/client/interfaces/db.py:2050 ../../lib/entropy/qa.py:701
#: ../../client/solo/commands/rescue.py:312
#: ../../client/solo/commands/rescue.py:323
#: ../../client/solo/commands/install.py:525
#: ../../client/solo/commands/install.py:528
#: ../../client/solo/commands/install.py:535
#: ../../client/solo/commands/install.py:538
msgid "Attention"
msgstr "注目"

#: ../../lib/kswitch/__init__.py:124
msgid "some external drivers cannot work across multiple kernels."
msgstr "一部の外部ドライバは、複数のカーネルまたがって動作することはできません。"

#: ../../lib/kswitch/__init__.py:125
msgid "Please reboot your computer now !"
msgstr "今、コンピュータを再起動してください！"

#: ../../lib/kswitch/__init__.py:201
msgid ""
"is not installed. Unable to resolve kernel packages correctly. Please use "
"--from-running or installthe package. Is your system up-to-date?"
msgstr ""

#: ../../lib/kswitch/__init__.py:218
msgid "Unable to resolve the latest kernel metadata. Try again later."
msgstr ""

#: ../../lib/kswitch/__init__.py:224
msgid "Resolving virtual kernel package"
msgstr ""

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:249
msgid "Accessibility"
msgstr "接近できること"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:251
msgid "Accessibility applications"
msgstr "補助アプリケーション"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:255
msgid "Office"
msgstr "オフィス"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:256
msgid "Applications used in office environments"
msgstr "オフィス環境で使用されるアプリケーション"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:262
msgid "Development"
msgstr "開発"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:263
msgid "Applications or system libraries"
msgstr "アプリケーションやシステムライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:267
msgid "System"
msgstr "システム"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:268
msgid "System applications or libraries"
msgstr "システムアプリケーションやライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:272
msgid "Games"
msgstr "ゲーム"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:273
msgid "Games, enjoy your spare time"
msgstr "ゲームは、あなたの暇な時間を楽しむ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:277
msgid "GNOME Desktop"
msgstr "GNOMEデスクトップ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:279
msgid "Applications and libraries for the GNOME Desktop"
msgstr "アプリケーションおよびGNOMEデスクトップ用ライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:283
msgid "KDE Desktop"
msgstr "KDEデスクトップ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:285
msgid "Applications and libraries for the KDE Desktop"
msgstr "アプリケーションおよび KDE デスクトップ用ライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:289
msgid "XFCE Desktop"
msgstr "XFCE デスクトップ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:291
msgid "Applications and libraries for the XFCE Desktop"
msgstr "アプリケーションおよび XFCE デスクトップ用ライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:295
msgid "LXDE Desktop"
msgstr "LXDE デスクトップ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:297
msgid "Applications and libraries for the LXDE Desktop"
msgstr "アプリケーションおよび LXDE デスクトップ用ライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:301
msgid "Multimedia"
msgstr "複合媒体"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:303
msgid "Applications and libraries for Multimedia"
msgstr "アプリケーションやマルチメディアのためのライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:307
msgid "Networking"
msgstr "ネットワーキング"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:309
msgid "Applications and libraries for Networking"
msgstr "アプリケーションとネットワークのためのライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:313
msgid "Science"
msgstr "科学"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:315
msgid "Scientific applications and libraries"
msgstr "科学的なアプリケーションとライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:319
msgid "Security"
msgstr "警備"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:321
msgid "Security oriented applications"
msgstr "セキュリティ指向のアプリケーション"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:325
msgid "X11"
msgstr "X11"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:327
msgid "Applications and libraries for X11"
msgstr "アプリケーションとX11用のライブラリ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:625
msgid "Reloading Portage modules"
msgstr "Portageのモジュールをリロードする"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:1015
msgid "updating metadata"
msgstr "更新メタデータ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:1181
msgid "error"
msgstr "エラー"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:1183
msgid "not readable"
msgstr "読めない"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2680
msgid "package not available on system"
msgstr "システムで利用できないパッケージ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2689
msgid "repackaging"
msgstr "再パッケージ"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2701
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2895
msgid "WARNING"
msgstr "警告"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2702
msgid "Cannot complete quickpkg for atom"
msgstr "原子が（quickpkg）迅速なパッケージを完成することはできません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2704
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2898
msgid "do it manually"
msgstr "手動で行う"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2722
msgid "package files rebuild did not run properly"
msgstr "パッケージファイルが正しく実行されなかった再構築"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2723
msgid "Please update packages manually"
msgstr "パッケージを手動で更新してください"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2859
msgid "forcing package updates"
msgstr "パッケージの更新を強制的に"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2860
msgid "Syncing with"
msgstr "と同期"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:2896
msgid "Cannot complete quickpkg for atoms"
msgstr "原子のために（クイックパッケージ）quickpkgを完了することはできません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3260
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4983
#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:284
#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:535
msgid "QA"
msgstr "品質保証"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3261
msgid "Cannot update Portage package metadata"
msgstr "Portageのパッケージのメタデータを更新できません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3287
msgid "SPM uid update error"
msgstr "SPMのUIDの更新エラー"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3321
msgid "Cannot update SPM installed pkgs file"
msgstr "SPMインストールされたパッケージファイルを更新することはできません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3423
msgid "Portage world file is corrupted"
msgstr "Portageのワールドファイルが壊れています"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3515
msgid "preserved libraries have been found on system"
msgstr "保存ライブラリは、システム上で発見されている"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3660
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3808
msgid "does not exist"
msgstr "存在しません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3660
msgid "Overwriting"
msgstr "重ね書き"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3706
msgid "variable differs"
msgstr "変数が異なる"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3706
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3793
msgid "Updating"
msgstr "更新"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3721
msgid "updating critical variables"
msgstr "重要な変数を更新"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3793
msgid "differs"
msgstr "が異なる"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3808
msgid "Reverting"
msgstr "元に戻す"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:3823
msgid "Skipping configuration files update, you are not root."
msgstr "Skipping configuration files update, you are not root."

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4107
msgid "Error calculating dependencies"
msgstr "エラーの依存関係を計算する"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4670
msgid "not supported"
msgstr "サポートされていません"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4671
msgid "Probably Portage API has changed"
msgstr "おそらくPortageのAPIが変更されました"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4734
#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4820
msgid "IOError while reading"
msgstr "IOError：（入力/出力エラー）の読み込み中に"

#: ../../lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py:4984
msgid "illegal Entropy package tag in ebuild"
msgstr "ebuildの違法エントロピーパッケージタグ"

#: ../../lib/entropy/client/services/interfaces.py:61
msgid "Unknown documents"
msgstr "不明な書類"

#: ../../lib/entropy/client/services/interfaces.py:62
msgid "Comments"
msgstr "注釈"

#. BBCODE_TYPE_ID: _('BBcode Documents'),
#: ../../lib/entropy/client/services/interfaces.py:64
msgid "Images/Screenshots"
msgstr "画像/スクリーンショット"

#: ../../lib/entropy/client/services/interfaces.py:65
msgid "Generic Files"
msgstr "一般的なファイル"

#: ../../lib/entropy/client/services/interfaces.py:66
msgid "Videos"
msgstr "ビデオ"

#: ../../lib/entropy/client/services/interfaces.py:67
msgid "Icons"
msgstr "アイコン"

#: ../../lib/entropy/client/services/interfaces.py:70
msgid "Unknown document"
msgstr "不明な書類"

#: ../../lib/entropy/client/services/interfaces.py:71
msgid "Comment"
msgstr "注釈"

#. BBCODE_TYPE_ID: _('BBcode Document'),
#: ../../lib/entropy/client/services/interfaces.py:73
msgid "Image/Screenshot"
msgstr "画像/スクリーンショット"

#: ../../lib/entropy/client/services/interfaces.py:74
msgid "Generic File"
msgstr "一般的なファイル"

#: ../../lib/entropy/client/services/interfaces.py:75
msgid "Video"
msgstr "ビデオ"

#: ../../lib/entropy/client/services/interfaces.py:76
msgid "Icon"
msgstr "アイコン"

#: ../../lib/entropy/client/misc.py:250
msgid "Automerging file"
msgstr "自動マージファイル"

#: ../../lib/entropy/client/misc.py:284
msgid "Found update"
msgstr "ある更新"

#: ../../lib/entropy/client/interfaces/sets.py:240
msgid "Name already taken"
msgstr "名前は既に使用されて"

#: ../../lib/entropy/client/interfaces/sets.py:255
msgid "Cannot create the element"
msgstr "要素を作成できません"

#: ../../lib/entropy/client/interfaces/sets.py:275
msgid "cannot start with"
msgstr "で始めることはできません。"

#: ../../lib/entropy/client/interfaces/sets.py:280
msgid "Already removed"
msgstr "既に削除"

#: ../../lib/entropy/client/interfaces/sets.py:284
msgid "Not defined by user"
msgstr "ユーザーによって定義されていません"

#: ../../lib/entropy/client/interfaces/sets.py:292
msgid "Set not found or unable to remove"
msgstr "設定し見つからないか、削除することができませんではない"

#: ../../lib/entropy/client/interfaces/methods.py:92
msgid "Please update your repositories now in order to remove this message!"
msgstr "このメッセージを除去するために、今、あなたのリポジトリを更新してください！"

#: ../../lib/entropy/client/interfaces/methods.py:111
#: ../../lib/entropy/client/interfaces/methods.py:136
#: ../../client/solo/commands/upgrade.py:305
msgid "Repository"
msgstr "リポジトリ"

#: ../../lib/entropy/client/interfaces/methods.py:112
#: ../../client/solo/commands/pkg.py:190
#: ../../client/solo/commands/mask.py:101
msgid "is not available"
msgstr "利用できない"

#: ../../lib/entropy/client/interfaces/methods.py:112
#: ../../lib/entropy/client/interfaces/methods.py:137
msgid "Cannot validate"
msgstr "検証できません"

#: ../../lib/entropy/client/interfaces/methods.py:137
msgid "is corrupted"
msgstr "破損している"

#: ../../lib/entropy/client/interfaces/methods.py:290
msgid "bad repository id specified"
msgstr "悪いリポジトリIDが指定されました"

#: ../../lib/entropy/client/interfaces/methods.py:315
#, python-format
msgid "Repository %s hasn't been downloaded yet."
msgstr "リポジトリ %s がまだダウンロードされていません。"

#: ../../lib/entropy/client/interfaces/methods.py:1070
msgid "System database not found or corrupted"
msgstr "システムデータベースが見つからないか、破損していない"

#: ../../lib/entropy/client/interfaces/methods.py:1071
msgid "running in safe mode using temporary, empty repository"
msgstr "一時、空のリポジトリを使用してセーフモードで実行されている"

#: ../../lib/entropy/client/interfaces/methods.py:1259
msgid "Backing up repository to"
msgstr "に、リポジトリのバックアップ"

#: ../../lib/entropy/client/interfaces/methods.py:1279
msgid "Repository backed up successfully"
msgstr "リポジトリには、正常にバックアップ"

#: ../../lib/entropy/client/interfaces/methods.py:1288
#: ../../lib/entropy/client/interfaces/methods.py:1346
#: ../../lib/entropy/const.py:629
msgid "All fine"
msgstr "すべての罰金"

#: ../../lib/entropy/client/interfaces/methods.py:1307
msgid "Restoring backed up repository"
msgstr "バックアップしたリポジトリを復元する"

#: ../../lib/entropy/client/interfaces/methods.py:1325
msgid "Unable to unpack"
msgstr "解凍することができません"

#: ../../lib/entropy/client/interfaces/methods.py:1335
msgid "Repository restored successfully"
msgstr "リポジトリ正常に復元"

#: ../../lib/entropy/client/interfaces/methods.py:1477
#: ../../lib/entropy/client/interfaces/package/actions/remove.py:129
#: ../../lib/entropy/client/interfaces/package/actions/remove.py:136
msgid "Removing"
msgstr "削除"

#: ../../lib/entropy/client/interfaces/methods.py:1891
msgid "Checking speed of"
msgstr "の速度を確認する"

#: ../../lib/entropy/client/interfaces/methods.py:1922
msgid "Mirror speed"
msgstr "ミラー速度"

#: ../../lib/entropy/client/interfaces/methods.py:2475
msgid "not a valid method"
msgstr "ではない有効なメソッド"

#: ../../lib/entropy/client/interfaces/db.py:309
msgid "Injecting downloaded dump"
msgstr "ダウンロードされたダンプを注入"

#: ../../lib/entropy/client/interfaces/db.py:411
msgid "Scanning URL"
msgstr "スキャンのURL"

#: ../../lib/entropy/client/interfaces/db.py:433
msgid "Selected URL"
msgstr "選択されたURL"

#: ../../lib/entropy/client/interfaces/db.py:457
msgid "repository is not available at the database URLs"
msgstr "リポジトリは、データベースのURLで利用できません"

#: ../../lib/entropy/client/interfaces/db.py:464
msgid "Looking for an alternate route using package mirrors"
msgstr "パッケージミラーを使用して代替ルートを探して"

#: ../../lib/entropy/client/interfaces/db.py:473
msgid "Checking repository URL"
msgstr "リポジトリのURLをチェックする"

#: ../../lib/entropy/client/interfaces/db.py:496
msgid "Found repository at URL"
msgstr "URLにあるリポジトリ"

#: ../../lib/entropy/client/interfaces/db.py:508
msgid "Unable to find alternate repository mirrors. Sorry."
msgstr "別のリポジトリのミラーを見つけることができません。申し訳ありません。"

#: ../../lib/entropy/client/interfaces/db.py:530
#: ../../client/solo/commands/status.py:153
msgid "Repository URL"
msgstr "リポジトリURL"

#: ../../lib/entropy/client/interfaces/db.py:540
msgid "Repository local path"
msgstr "リポジトリのローカルパス"

#: ../../lib/entropy/client/interfaces/db.py:548
msgid "Repository API"
msgstr "リポジトリAPI"

#: ../../lib/entropy/client/interfaces/db.py:598
msgid "Downloading repository"
msgstr "ダウンロードリポジトリ"

#: ../../lib/entropy/client/interfaces/db.py:648
msgid "unable to download the repository"
msgstr "リポジトリをダウンロードすることができません"

#: ../../lib/entropy/client/interfaces/db.py:669
msgid "Downloading checksum"
msgstr "チェックサムをダウンロード中"

#: ../../lib/entropy/client/interfaces/db.py:696
msgid "Cannot fetch checksum"
msgstr "チェックサムをフェッチできません"

#: ../../lib/entropy/client/interfaces/db.py:697
#: ../../lib/entropy/client/interfaces/db.py:1287
msgid "Cannot verify repository integrity"
msgstr "リポジトリの整合性を検証できません"

#: ../../lib/entropy/client/interfaces/db.py:794
msgid "Unpacking database to"
msgstr "にデータベースを解凍"

#: ../../lib/entropy/client/interfaces/db.py:811
msgid "Cannot unpack compressed package"
msgstr "圧縮されたパッケージを解凍することはできません"

#: ../../lib/entropy/client/interfaces/db.py:812
msgid "Skipping repository"
msgstr "スキップリポジトリ"

#: ../../lib/entropy/client/interfaces/db.py:840
msgid "Repository is invalid"
msgstr "リポジトリが無効です"

#: ../../lib/entropy/client/interfaces/db.py:864
msgid "Indexing Repository metadata"
msgstr "インデックス作成リポジトリのメタデータ"

#: ../../lib/entropy/client/interfaces/db.py:1092
msgid "Downloading repository metafile"
msgstr "リポジトリメタファイルのダウンロード"

#: ../../lib/entropy/client/interfaces/db.py:1102
msgid "Downloading GPG signature of repository metafile"
msgstr "リポジトリメタファイルのダウンロードGPG署名"

#: ../../lib/entropy/client/interfaces/db.py:1112
msgid "Downloading Notice Board"
msgstr "掲示板のダウンロード"

#: ../../lib/entropy/client/interfaces/db.py:1138
msgid "unpacked meta file"
msgstr "アンパックメタファイル"

#: ../../lib/entropy/client/interfaces/db.py:1144
msgid "removed meta file"
msgstr "削除するメタファイル"

#: ../../lib/entropy/client/interfaces/db.py:1161
msgid "not available, it's ok"
msgstr "利用できないが、それは大丈夫です！"

#: ../../lib/entropy/client/interfaces/db.py:1165
msgid "not available, not very ok!"
msgstr "利用できない、非常に大丈夫ではない！"

#: ../../lib/entropy/client/interfaces/db.py:1178
msgid "available, w00t!"
msgstr "利用可能です、やった！"

#: ../../lib/entropy/client/interfaces/db.py:1196
msgid "cannot be unpacked, not very ok!"
msgstr "非常に大丈夫ではない、アンパックすることはできません！"

#: ../../lib/entropy/client/interfaces/db.py:1249
msgid "Repository revision"
msgstr "リポジトリのリビジョン"

#: ../../lib/entropy/client/interfaces/db.py:1272
msgid "Checking downloaded repository"
msgstr "ダウンロードされたリポジトリをチェック"

#: ../../lib/entropy/client/interfaces/db.py:1286
msgid "Cannot open digest"
msgstr "ダイジェスト開くことができません"

#: ../../lib/entropy/client/interfaces/db.py:1297
#: ../../lib/entropy/client/interfaces/db.py:1308
msgid "Downloaded repository status"
msgstr "ダウンロードしたリポジトリのステータス"

#: ../../lib/entropy/client/interfaces/db.py:1298
msgid "OK"
msgstr "良し"

#: ../../lib/entropy/client/interfaces/db.py:1309
msgid "ERROR"
msgstr "誤差"

#: ../../lib/entropy/client/interfaces/db.py:1318
msgid "An error occurred while checking repository integrity"
msgstr "リポジトリの整合性をチェックするときにエラーが発生しました"

#: ../../lib/entropy/client/interfaces/db.py:1319
msgid "Giving up"
msgstr "断念"

#: ../../lib/entropy/client/interfaces/db.py:1341
#: ../../lib/entropy/security.py:397
msgid ""
"Make sure to verify the imported key and set an appropriate trust level"
msgstr "インポートしたキーを確認し、適切な信頼レベルを設定してください"

#: ../../lib/entropy/client/interfaces/db.py:1361
msgid "This repository suports GPG-signed packages"
msgstr "このレポジトリはGPG署名パッケージをサポートしています"

#: ../../lib/entropy/client/interfaces/db.py:1368
msgid "you may want to install GnuPG to take advantage of this feature"
msgstr "GnuPGをインストールすればこの機能を利用できるようになります"

#: ../../lib/entropy/client/interfaces/db.py:1403
#: ../../lib/entropy/security.py:437
msgid "GPG key changed for"
msgstr "GPG キーを変更"

#: ../../lib/entropy/client/interfaces/db.py:1423
#: ../../lib/entropy/security.py:456
msgid "GPG key already installed for"
msgstr "GPG キーが既にインストールされています"

#: ../../lib/entropy/client/interfaces/db.py:1436
msgid "GPG key EXPIRED for repository"
msgstr "レポジトリのGPGは期限切れです"

#: ../../lib/entropy/client/interfaces/db.py:1448
msgid "Installing GPG key for repository"
msgstr "レポジトリのGPG鍵をインストールしています"

#: ../../lib/entropy/client/interfaces/db.py:1466
#: ../../lib/entropy/client/interfaces/db.py:1499
#: ../../lib/entropy/security.py:493
msgid "Error during GPG key installation"
msgstr "GPG キーのインストール時のエラー"

#: ../../lib/entropy/client/interfaces/db.py:1476
msgid "GPG key seems already installed but not properly recorded, resetting"
msgstr "GPGキーがすでにインストールされていますが、正常にリセットし、記録されていないようです"

#: ../../lib/entropy/client/interfaces/db.py:1511
msgid "Successfully installed GPG key for repository"
msgstr "レポジトリのGPG鍵のインストールに成功しました"

#: ../../lib/entropy/client/interfaces/db.py:1520
#: ../../lib/entropy/security.py:513
msgid "Fingerprint"
msgstr "指紋"

#: ../../lib/entropy/client/interfaces/db.py:1558
msgid "Verifying GPG signature of"
msgstr "GPG証明を検証中"

#: ../../lib/entropy/client/interfaces/db.py:1572
msgid "Verified GPG signature of"
msgstr "GPG証明を検証しました"

#: ../../lib/entropy/client/interfaces/db.py:1582
#: ../../lib/entropy/security.py:541
msgid "Error during GPG verification of"
msgstr "GPG 検証中のエラー"

#: ../../lib/entropy/client/interfaces/db.py:1591
#: ../../lib/entropy/security.py:550
msgid "It could mean a potential security risk"
msgstr "セキュリティ リスクの可能性を意味するかもしれない"

#: ../../lib/entropy/client/interfaces/db.py:1649
msgid "Web Service"
msgstr "ウェブサービス"

#: ../../lib/entropy/client/interfaces/db.py:1650
msgid "skipping differential sync"
msgstr "差分同期をスキップ"

#: ../../lib/entropy/client/interfaces/db.py:1651
msgid "threshold"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1685
msgid "Web Service communication error"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1705
msgid "Web Service data error"
msgstr "ウェブサービスデータエラー"

#: ../../lib/entropy/client/interfaces/db.py:1721
msgid "Local status"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1753
msgid "Fetching segments"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1789
#: ../../lib/entropy/client/interfaces/db.py:1808
#: ../../lib/entropy/client/interfaces/db.py:1825
msgid "Web Service status"
msgstr "ウェブサービスの状態"

#: ../../lib/entropy/client/interfaces/db.py:1790
msgid "cannot fetch repository metadata"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1809
msgid "cannot update treeupdates data"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1826
msgid "cannot update package sets data"
msgstr "パッケージ集合のデータを更新できません"

#: ../../lib/entropy/client/interfaces/db.py:1842
msgid "Fetch error on segment while adding"
msgstr ""

#: ../../lib/entropy/client/interfaces/db.py:1868
msgid "repository error while adding packages"
msgstr "パッケージ追加中にレポジトリーエラー"

#: ../../lib/entropy/client/interfaces/db.py:1891
msgid "repository error while removing packages"
msgstr "パッケージ削除中にレポジトリーエラー"

#: ../../lib/entropy/client/interfaces/db.py:1907
msgid "Repository checksum doesn't match remote."
msgstr "レポジトリチェックサムがリモートと一致しません。"

#: ../../lib/entropy/client/interfaces/db.py:1910
msgid "local"
msgstr "ローカル"

#: ../../lib/entropy/client/interfaces/db.py:1915
msgid "remote"
msgstr "リモート"

#: ../../lib/entropy/client/interfaces/db.py:2038
msgid "repository is already up to date"
msgstr "レポジトリは最新です"

#: ../../lib/entropy/client/interfaces/db.py:2051
msgid "Repository is being updated"
msgstr "レポジトリを更新しています"

#: ../../lib/entropy/client/interfaces/db.py:2052
msgid "Try again in a few minutes"
msgstr "数分後にお試しください"

#: ../../lib/entropy/client/interfaces/db.py:2248
msgid "Configuration files update error, not critical, continuing"
msgstr "設定ファイルの更新エラー、重要ではない、継続的な"

#: ../../lib/entropy/client/interfaces/client.py:371
msgid "forcing packages metadata update"
msgstr "強制パッケージメタデータの更新"

#: ../../lib/entropy/client/interfaces/client.py:380
msgid "Updating system database using repository"
msgstr "リポジトリを使用して更新システムデータベース"

#: ../../lib/entropy/client/interfaces/repository.py:194
msgid "Something bad happened. Please have a look."
msgstr ""

#: ../../lib/entropy/client/interfaces/repository.py:213
msgid "there is"
msgid_plural "there are"
msgstr[0] ""

#: ../../lib/entropy/client/interfaces/repository.py:215
msgid "package file that could be removed"
msgid_plural "package files that could be removed"
msgstr[0] "削除できないパッケージファイル"

#: ../../lib/entropy/client/interfaces/repository.py:228
msgid "Packages are stored in"
msgstr "パッケージは保存されています"

#: ../../lib/entropy/client/interfaces/repository.py:298
msgid "Advisories fetch error"
msgstr ""

#: ../../lib/entropy/client/interfaces/repository.py:315
msgid "Repositories synchronization"
msgstr ""

#: ../../lib/entropy/client/interfaces/dep.py:53
#, python-format
msgid "Checking %s"
msgstr "%sを確認中"

#: ../../lib/entropy/client/interfaces/dep.py:2225
msgid "Sorting dependencies"
msgstr "依存関係を整理中"

#: ../../lib/entropy/client/interfaces/dep.py:2510
msgid "Calculating inverse dependencies for"
msgstr ""

#: ../../lib/entropy/client/interfaces/dep.py:3230
msgid "Calculating updates"
msgstr "更新内容を計算中"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:604
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:691
msgid "Mirror"
msgstr "ミラー"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:606
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:693
msgid "maximum failure threshold reached"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:657
msgid "success"
msgstr "成功"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:670
msgid "Aggregated transfer rate"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:673
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:754
#: ../../lib/entropy/client/interfaces/package/actions/source.py:176
msgid "second"
msgstr "セカンド"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:689
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:771
#: ../../lib/entropy/client/interfaces/package/actions/source.py:197
msgid "Error downloading from"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:694
msgid "data not available on this mirror"
msgstr "このミラーではデータが利用できません"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:697
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:782
msgid "wrong checksum"
msgstr "不正なチェックサム"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:700
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:794
msgid "not found"
msgstr "見つからない"

#. timeout!
#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:703
msgid "timeout error"
msgstr "タイムアウトエラー"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:706
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:807
#: ../../lib/entropy/client/interfaces/package/actions/source.py:207
msgid "discarded download"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:710
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:810
#: ../../lib/entropy/client/interfaces/package/actions/source.py:210
msgid "unknown reason"
msgstr "未知の理由"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:822
#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:830
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:844
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:865
#: ../../lib/entropy/client/interfaces/package/actions/source.py:151
#: ../../client/solo/utils.py:276 ../../client/solo/commands/command.py:367
msgid "Downloading"
msgstr "ダウンロード中"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:824
#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:832
#: ../../client/solo/commands/query.py:1286
#: ../../client/solo/commands/_manage.py:610
msgid "package"
msgid_plural "packages"
msgstr[0] "パッケージ"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:846
msgid "Some packages cannot be fetched"
msgstr "いくつかのパッケージを取り出すことができません"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:847
msgid "Try to update your repositories and retry"
msgstr "レポジトリを更新して再実行してみてください"

#: ../../lib/entropy/client/interfaces/package/actions/multifetch.py:860
#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:853
#: ../../lib/entropy/client/interfaces/package/actions/install.py:629
#: ../../lib/entropy/client/interfaces/package/actions/install.py:1323
#: ../../lib/entropy/client/interfaces/package/actions/config.py:144
#: ../../lib/entropy/client/interfaces/package/actions/config.py:164
#: ../../client/solo/commands/rescue.py:206
msgid "Error"
msgstr "エラー"

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:285
msgid "Cannot run External trigger for"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:287
#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:539
msgid "Please report it"
msgstr "それを報告してください"

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:499
msgid "Installing info"
msgstr "インストール情報"

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:522
msgid "Package phase"
msgstr "パッケージフェーズ"

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:536
msgid "Cannot run phase"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:550
#: ../../lib/entropy/client/interfaces/package/actions/config.py:112
msgid "Source Package Manager is too old, please update it"
msgstr "Source Package Managerが古すぎます。更新してください。"

#: ../../lib/entropy/client/interfaces/package/actions/_triggers.py:563
msgid "Source Package Manager phase error"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/remove.py:86
#: ../../lib/entropy/client/interfaces/package/actions/install.py:860
msgid "Pre-remove"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/remove.py:115
msgid "The requested package is no longer available"
msgstr "要求されたパッケージは利用できなくなりました。"

#: ../../lib/entropy/client/interfaces/package/actions/remove.py:149
msgid "Removing from Entropy"
msgstr "エントロピーから削除"

#: ../../lib/entropy/client/interfaces/package/actions/remove.py:234
#: ../../lib/entropy/client/interfaces/package/actions/install.py:926
msgid "Post-remove"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/action.py:221
msgid "An error occurred. Action aborted."
msgstr "エラーが発生しました。アクションが中止されました。"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:722
msgid "Downloading from"
msgstr "ダウンロード中"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:748
#: ../../lib/entropy/client/interfaces/package/actions/source.py:172
msgid "Successfully downloaded from"
msgstr "ダウンロード成功"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:753
#: ../../lib/entropy/client/interfaces/package/actions/source.py:174
msgid "at"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:778
#: ../../lib/entropy/client/interfaces/package/actions/source.py:202
msgid "file not available on this mirror"
msgstr "このミラーではファイルが利用できません"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:788
msgid "Disabling resume"
msgstr "履歴書を無効にする"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:800
msgid "timeout, retrying on this mirror"
msgstr "このミラーのタイムアウト、再試行"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:803
msgid "timeout, giving up"
msgstr "タイムアウト、あきらめる"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:851
msgid "Package cannot be downloaded. Try to update repositories"
msgstr "パッケージはダウンロードできません。リポジトリを更新しよう"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1038
msgid "Package signature verification error for"
msgstr "パッケージ署名検証エラー"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1071
msgid "disabled"
msgstr "無効"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1090
msgid "Package signature verification"
msgstr "パッケージ署名検証"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1092
msgid "temporarily unavailable"
msgstr "一時的に利用不可"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1104
msgid "Package signature"
msgstr "パッケージ署名"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1106
msgid "does not match the recorded one"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1118
msgid "validated"
msgstr "有効な"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1128
msgid "Checking package checksum..."
msgstr "パッケージのチェックサムを検証中"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1146
msgid "Checksum validation error"
msgstr "チェックサム検証エラー"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1160
msgid "Invalid checksum"
msgstr "無効なチェックサム"

#: ../../lib/entropy/client/interfaces/package/actions/fetch.py:1178
msgid "Invalid signatures"
msgstr "無効な署名"

#: ../../lib/entropy/client/interfaces/package/actions/source.py:117
msgid "Fetch path setup error"
msgstr "パス設定エラーをフェッチ"

#: ../../lib/entropy/client/interfaces/package/actions/source.py:138
msgid "Source code not available."
msgstr "ソースコードは利用できません。"

#: ../../lib/entropy/client/interfaces/package/actions/source.py:187
msgid "Local path"
msgstr "ローカルパス"

#: ../../lib/entropy/client/interfaces/package/actions/source.py:227
msgid "Fetching sources"
msgstr "ソースを取得中"

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:79
msgid "Protecting"
msgstr "保護"

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:81
msgid "library needed by:"
msgstr "が必要とするライブラリ："

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:123
msgid "Removing library"
msgstr "ライブラリの削除"

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:151
msgid "Failed to remove the library"
msgstr "ライブラリの削除に失敗しました"

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:343
msgid "Cannot protect broken symlink"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:377
msgid "Skipping file installation/removal"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:421
#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:539
msgid "Protecting config file"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:516
msgid "Removing config file, never modified"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:538
msgid "remove"
msgstr "退ける"

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:558
msgid "This package contains a badly encoded file !!!"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/_manage.py:687
msgid "Collision found during removal of"
msgstr "削除中に衝突が検知されました"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:404
#: ../../lib/entropy/client/interfaces/package/actions/install.py:619
msgid "Unpacking"
msgstr "解凍中"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:444
msgid "Unpack error"
msgstr "解凍エラー"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:476
msgid "Unable to find Entropy metadata in package"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:515
msgid "Unable to unpack package"
msgstr "パッケージを展開することができません"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:586
msgid "Merging"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:592
msgid "Merging package"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:625
msgid "An error occurred while trying to unpack the package"
msgstr "パッケージを展開しようとしたときにエラーが発生しました"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:628
#: ../../lib/entropy/client/interfaces/package/actions/install.py:1322
msgid "Check if your system is healthy"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:711
msgid "Setup"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:741
msgid "Pre-install"
msgstr "プレインストール"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:790
#: ../../lib/entropy/client/interfaces/package/actions/install.py:804
msgid "Error during package files permissions setup"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:897
msgid "Cleaning previously installed application data."
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:983
msgid "Post-install"
msgstr "インストール後"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1010
#: ../../lib/entropy/client/interfaces/package/actions/install.py:1016
#: ../../client/solo/utils.py:67
msgid "Cleaning"
msgstr "クリーニング中"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1321
msgid "An error occurred while trying to install the package"
msgstr "パッケージをインストール中にエラーが発生しました"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1335
msgid "Updating installed packages repository"
msgstr "インストールされたパッケージのリポジトリを更新"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1367
msgid "Installing"
msgstr "インストール中"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1373
msgid "Installing package"
msgstr "パッケージをインストール"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1395
msgid "unsupported splitdebug usage (package files)"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1399
msgid "<3 debug files installation enabled <3"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1497
msgid "Collision found during install for"
msgstr "インストール中に衝突が検知されました"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1499
msgid "QA:"
msgstr "QA:"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1501
msgid "cannot overwrite"
msgstr "上書きできません"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1585
#, python-format
msgid "QA: %s is a file when it should be a directory"
msgstr "QA：%s それはディレクトリでなければならないときにファイルである"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1610
msgid "File moved"
msgstr "ファイルを移動"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1632
msgid "QA: symlink expected, directory found"
msgstr "QA：シンボリックリンクと予想、ディレクトリ発見"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1666
msgid "Cannot remove symlink"
msgstr ""

#. we can merge it, files, even if
#. contains changes have not been modified
#. by the user
#: ../../lib/entropy/client/interfaces/package/actions/install.py:1844
msgid "Automerging config file, never modified"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1873
#: ../../lib/entropy/client/interfaces/package/actions/install.py:1895
msgid "QA: circular symlink issue"
msgstr "QA：円形のシンボリックリンクの問題"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1935
msgid "Fatal: file expected, directory found"
msgstr "致命的：ファイル期待、ディレクトリ発見"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1975
msgid "QA: file move error"
msgstr "QA：ファイルの移動エラー"

#: ../../lib/entropy/client/interfaces/package/actions/install.py:1978
msgid "please report"
msgstr "報告してください"

#: ../../lib/entropy/client/interfaces/package/actions/config.py:85
msgid "configuration phase"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/config.py:141
#: ../../lib/entropy/client/interfaces/package/actions/config.py:161
msgid "An error occurred while trying to configure the package"
msgstr "パッケージを設定中にエラーが発生しました"

#: ../../lib/entropy/client/interfaces/package/actions/config.py:143
msgid "Make sure that your system is healthy"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/config.py:163
msgid "It seems that Source Package Manager entry is missing"
msgstr ""

#: ../../lib/entropy/client/interfaces/package/actions/config.py:190
msgid "The requested package is no longer available."
msgstr "要求されたパッケージは利用できなくなりました。"

#: ../../lib/entropy/client/interfaces/package/actions/config.py:212
#: ../../lib/entropy/client/interfaces/package/actions/config.py:218
msgid "Configuring package"
msgstr ""

#: ../../lib/entropy/fetchers.py:889
msgid "infinite"
msgstr "無限"

#: ../../lib/entropy/fetchers.py:961
msgid "[F]"
msgstr "[F]"

#: ../../lib/entropy/fetchers.py:962 ../../lib/entropy/fetchers.py:1390
msgid "ETA"
msgstr "ETA"

#: ../../lib/entropy/fetchers.py:963 ../../lib/entropy/fetchers.py:1391
msgid "sec"
msgstr "sec"

#: ../../lib/entropy/fetchers.py:1254
msgid "Aggregated download"
msgstr "集約されたダウンロード"

#: ../../lib/entropy/fetchers.py:1256
msgid "item"
msgid_plural "items"
msgstr[0] "項目"

#: ../../lib/entropy/security.py:469
msgid "GPG key EXPIRED for URL"
msgstr "URL の GPG キー期限切れ"

#: ../../lib/entropy/security.py:479
msgid "Installing GPG key for URL"
msgstr "GPG キー URL をインストールします。"

#: ../../lib/entropy/security.py:504
msgid "Successfully installed GPG key for URL"
msgstr "GPG キーの URL は正常にインストール"

#: ../../lib/entropy/security.py:561 ../../lib/entropy/security.py:880
#: ../../lib/entropy/security.py:916 ../../lib/entropy/security.py:921
#: ../../lib/entropy/security.py:989 ../../lib/entropy/security.py:1018
#: ../../lib/entropy/security.py:1030 ../../lib/entropy/security.py:1050
#: ../../lib/entropy/security.py:1061 ../../lib/entropy/security.py:1086
#: ../../lib/entropy/security.py:1121
msgid "Security Advisories"
msgstr "セキュリティ アドバイザリ"

#: ../../lib/entropy/security.py:562
msgid "GPG key verification successful"
msgstr "GPG キー検証の成功"

#: ../../lib/entropy/security.py:722 ../../client/solo/commands/_manage.py:418
#: ../../client/solo/commands/_manage.py:451
#: ../../client/solo/commands/pkg.py:188 ../../client/solo/commands/mask.py:99
#: ../../client/solo/commands/mask.py:172
msgid "Warning"
msgstr "警告"

#: ../../lib/entropy/security.py:724
msgid "broken advisory"
msgstr "壊れた顧問"

#: ../../lib/entropy/security.py:881
msgid "getting latest advisories"
msgstr "最新の勧告を取得"

#: ../../lib/entropy/security.py:898
msgid "cannot create temporary directory"
msgstr "一時ディレクトリを作成することはできません"

#: ../../lib/entropy/security.py:917
msgid "updated successfully"
msgstr "正常に更新されました"

#: ../../lib/entropy/security.py:922
msgid "already up to date"
msgstr "既に最新の状態"

#: ../../lib/entropy/security.py:990
msgid "cannot download checksum, sorry"
msgstr "チェックサムをダウンロードできません申し訳ありません"

#: ../../lib/entropy/security.py:1019
msgid "unable to download advisories, sorry"
msgstr "勧告をダウンロードすることができません申し訳ありません"

#: ../../lib/entropy/security.py:1031
msgid "Verifying checksum"
msgstr "チェックサムの検証"

#: ../../lib/entropy/security.py:1051
msgid "verification successful"
msgstr "検証が完了しました"

#: ../../lib/entropy/security.py:1062
msgid "checksum verification failed, sorry"
msgstr "チェックサム検証は申し訳ありませんが、失敗しました。"

#: ../../lib/entropy/security.py:1087
msgid "GPG service not available"
msgstr "GPG サービスは利用できません。"

#: ../../lib/entropy/security.py:1122
msgid "digest verification failed, try again later"
msgstr "ダイジェストの検証に失敗しました, もう一度お試しください。"

#: ../../lib/entropy/const.py:607
msgid "Runtime dependency"
msgstr "実行時の依存関係"

#: ../../lib/entropy/const.py:608
msgid "Post dependency"
msgstr "依存関係を記事します。"

#: ../../lib/entropy/const.py:609
msgid "Manually added (by staff) dependency"
msgstr "（スタッフ） を手動で追加した依存関係"

#: ../../lib/entropy/const.py:610
msgid "Build dependency"
msgstr "依存関係を構築"

#: ../../lib/entropy/const.py:630
msgid "Corrupted Client Repository. Please restore a backup."
msgstr "クライアントレポジトリが破損しています。バックアップから復元してください。"

#: ../../lib/entropy/const.py:662
msgid "reason not available"
msgstr "利用できない理由"

#: ../../lib/entropy/const.py:663
msgid "user package.mask"
msgstr "ユーザー package.mask"

#: ../../lib/entropy/const.py:664
msgid "system keywords"
msgstr "システムのキーワード"

#: ../../lib/entropy/const.py:665
msgid "user package.unmask"
msgstr "ユーザー にパッケージアンマスク(package.unmask)"

#: ../../lib/entropy/const.py:666
msgid "user repo package.keywords (all packages)"
msgstr "ユーザー レポ package.keywords (すべてのパッケージ)"

#: ../../lib/entropy/const.py:667
msgid "user repo package.keywords"
msgstr "ユーザーレポパッケージキーワード（package.keywords）"

#: ../../lib/entropy/const.py:668
msgid "user package.keywords"
msgstr "ユーザーパッケージのキーワード（package.keywords）"

#: ../../lib/entropy/const.py:669
msgid "completely masked (by keyword?)"
msgstr "完全にマスク (キーワードか？）"

#: ../../lib/entropy/const.py:670
msgid "repository general packages.db.mask"
msgstr "リポジトリの一般的な packages.db.mask"

#: ../../lib/entropy/const.py:671
msgid "repository general packages.db.keywords"
msgstr "リポジトリの一般のパッケージデータベースのキーワード（packages.db.keywords）"

#: ../../lib/entropy/const.py:672
msgid "user license.mask"
msgstr "ユーザーライセンスマスク（license.mask）"

#: ../../lib/entropy/const.py:673
msgid "user live unmask"
msgstr "ユーザーがライブの正体を暴露"

#: ../../lib/entropy/const.py:674
msgid "user live mask"
msgstr "ユーザー ライブ マスク"

#: ../../lib/entropy/output.py:637
msgid "Entropy needs your attention"
msgstr "エントロピーは、注意が必要"

#: ../../lib/entropy/output.py:780 ../../lib/entropy/output.py:1026
#: ../../client/solo/utils.py:487 ../../client/solo/commands/ugc.py:656
#: ../../client/solo/commands/ugc.py:766 ../../client/solo/commands/ugc.py:789
#: ../../client/solo/commands/ugc.py:970
#: ../../client/solo/commands/rescue.py:680
#: ../../client/solo/commands/rescue.py:685
#: ../../client/solo/commands/rescue.py:724
#: ../../client/solo/commands/upgrade.py:300
#: ../../client/solo/commands/upgrade.py:336
msgid "Yes"
msgstr "はい"

#: ../../lib/entropy/output.py:780 ../../client/solo/utils.py:489
#: ../../client/solo/main.py:168 ../../client/solo/commands/config.py:152
#: ../../client/solo/commands/conf.py:395
#: ../../client/solo/commands/conf.py:450
#: ../../client/solo/commands/remove.py:368
#: ../../client/solo/commands/deptest.py:198
#: ../../client/solo/commands/libtest.py:226
#: ../../client/solo/commands/rescue.py:333
#: ../../client/solo/commands/rescue.py:337
#: ../../client/solo/commands/rescue.py:344
#: ../../client/solo/commands/install.py:610
#: ../../client/solo/commands/upgrade.py:300
#: ../../client/solo/commands/mask.py:161
msgid "No"
msgstr "いいえ"

#: ../../lib/entropy/output.py:795
msgid "Entropy got a question for you"
msgstr "エントロピーはあなたのために質問したい"

#: ../../lib/entropy/output.py:809
msgid "Interrupted"
msgstr "中断"

#: ../../lib/entropy/output.py:872 ../../lib/entropy/output.py:876
msgid "Selected number"
msgstr "選択した数"

#: ../../lib/entropy/output.py:893 ../../client/solo/commands/_manage.py:723
msgid "Please select an option"
msgstr "オプションを選択してください。"

#: ../../lib/entropy/output.py:895
msgid "Discard all"
msgstr "すべてを捨てる"

#: ../../lib/entropy/output.py:896
msgid "Confirm"
msgstr "確認する"

#: ../../lib/entropy/output.py:897
msgid "Add item"
msgstr "アイテムの追加"

#: ../../lib/entropy/output.py:898
msgid "Edit item"
msgstr "編集項目"

#: ../../lib/entropy/output.py:899
msgid "Remove item"
msgstr "項目を削除"

#: ../../lib/entropy/output.py:900
msgid "Show current list"
msgstr "現在のリストを表示する"

#: ../../lib/entropy/output.py:904 ../../client/solo/commands/conf.py:251
#: ../../client/solo/commands/conf.py:294
msgid "Your choice (type a number and press enter):"
msgstr "あなたの選択 (入力番号を押します):"

#: ../../lib/entropy/output.py:936
msgid "You don't have typed a number."
msgstr "数値を入力したはありません。"

#: ../../lib/entropy/output.py:939
msgid "Invalid action."
msgstr "無効なアクション。"

#: ../../lib/entropy/output.py:949
msgid "String to add (-1 to go back):"
msgstr "(戻って-1) を追加する文字列:"

#: ../../lib/entropy/output.py:959
msgid "Invalid string."
msgstr "無効な文字列。"

#: ../../lib/entropy/output.py:967
msgid "Element number to edit (-1 to go back):"
msgstr "(戻って-1) を編集する要素の数:"

#: ../../lib/entropy/output.py:978
msgid "old"
msgstr "古い"

#: ../../lib/entropy/output.py:978
msgid "new value:"
msgstr "新しい値:"

#: ../../lib/entropy/output.py:986 ../../lib/entropy/output.py:1004
msgid "Invalid element."
msgstr "無効な要素。"

#: ../../lib/entropy/output.py:995
msgid "Element number to remove (-1 to go back):"
msgstr "(戻って-1) を削除する要素の数:"

#: ../../lib/entropy/qa.py:164
msgid "Searching for broken reverse dependencies"
msgstr "壊れた逆依存関係を検索する"

#: ../../lib/entropy/qa.py:181
msgid "scanning for broken reverse dependencies"
msgstr "壊れた逆依存関係をスキャンする"

#: ../../lib/entropy/qa.py:222
msgid "broken libraries detected"
msgstr "検出された破損したライブラリ"

#: ../../lib/entropy/qa.py:233
msgid "needs"
msgstr "ニーズに"

#: ../../lib/entropy/qa.py:272
msgid "scanning"
msgstr "スキャン"

#: ../../lib/entropy/qa.py:314
msgid "blacklisted dependencies !!!"
msgstr "ブラックリストに載って依存関係！"

#: ../../lib/entropy/qa.py:339
msgid "requires libraries"
msgstr "ライブラリが必要"

#: ../../lib/entropy/qa.py:357
msgid "library provided by"
msgstr "ライブラリが提供する"

#: ../../lib/entropy/qa.py:429
msgid "determining missing libraries"
msgstr "不足しているライブラリを決定する"

#: ../../lib/entropy/qa.py:473
msgid "requires"
msgstr "が必要です"

#: ../../lib/entropy/qa.py:489 ../../lib/entropy/qa.py:500
msgid "provided by"
msgstr "によって提供されます。"

#: ../../lib/entropy/qa.py:501
msgid "no packages"
msgstr "パッケージなし"

#: ../../lib/entropy/qa.py:513
msgid "no missing runtime libraries found"
msgstr "見つかっミッシング実行時ライブラリません"

#: ../../lib/entropy/qa.py:549
msgid "Libraries test"
msgstr "ライブラリのテスト"

#: ../../lib/entropy/qa.py:564
msgid "Broken symbols packages list"
msgstr "壊れたシンボルパッケージ一覧"

#: ../../lib/entropy/qa.py:565
msgid "Broken executables list"
msgstr "壊れた実行可能プログラムのリスト"

#: ../../lib/entropy/qa.py:567
msgid "Dumping results into these files"
msgstr "これらのファイルに結果をダンプ"

#: ../../lib/entropy/qa.py:644
msgid "discarding directory"
msgstr "ディレクトリの破棄"

#: ../../lib/entropy/qa.py:646
msgid "because it's symlinked on"
msgstr "シンボリック リンク上にあるため"

#: ../../lib/entropy/qa.py:696
msgid "Collecting broken executables"
msgstr "壊れた実行ファイルの収集"

#: ../../lib/entropy/qa.py:702
msgid "don't worry about libraries that are shown here but not later."
msgstr "ライブラリがここに示されている心配しないでください。"

#: ../../lib/entropy/qa.py:723
msgid "Scanning libraries"
msgstr "スキャンライブラリ"

#: ../../lib/entropy/qa.py:837
msgid "various broken symbols"
msgstr "様々な壊れたシンボル"

#: ../../lib/entropy/qa.py:876
msgid "Matching broken libraries/executables"
msgstr "壊れたライブラリ/実行可能プログラムと一致する"

#: ../../lib/entropy/qa.py:1677
msgid "Not prepared yet"
msgstr "まだ準備されていません"

#: ../../client/solo/utils.py:68
msgid "directory"
msgstr "ディレクトリ"

#: ../../client/solo/utils.py:76
msgid "Cleaned"
msgstr "削除しました"

#: ../../client/solo/utils.py:78
msgid "files and directories"
msgstr "ファイルとディレクトリ"

#: ../../client/solo/utils.py:199 ../../client/solo/utils.py:479
#: ../../client/solo/utils.py:481 ../../client/solo/commands/repo.py:505
#: ../../client/solo/commands/repo.py:560
msgid "N/A"
msgstr "N/A（適用されない）"

#: ../../client/solo/utils.py:278 ../../client/solo/commands/command.py:369
msgid "Uploading"
msgstr "アップロード"

#: ../../client/solo/utils.py:338 ../../client/solo/utils.py:374
#: ../../client/solo/utils.py:375 ../../client/solo/utils.py:579
msgid "n/a"
msgstr "n/a （該当なし）"

#: ../../client/solo/utils.py:373
msgid "Not installed"
msgstr "インストールされていません"

#: ../../client/solo/utils.py:400 ../../client/solo/commands/query.py:467
#: ../../client/solo/commands/query.py:716
#: ../../client/solo/commands/query.py:1042
msgid "Package"
msgstr "パッケージ"

#: ../../client/solo/utils.py:402 ../../client/solo/commands/hop.py:57
msgid "branch"
msgstr "支店"

#: ../../client/solo/utils.py:413
msgid "Category"
msgstr "カテゴリ"

#: ../../client/solo/utils.py:415
msgid "Name"
msgstr "名前"

#: ../../client/solo/utils.py:430 ../../client/solo/commands/query.py:581
msgid "Masked"
msgstr "仮面"

#: ../../client/solo/utils.py:433
msgid "Available"
msgstr "利用できる"

#: ../../client/solo/utils.py:435 ../../client/solo/utils.py:443
msgid "Installed"
msgstr "インストル"

#: ../../client/solo/utils.py:438 ../../client/solo/utils.py:444
msgid "version"
msgstr "バージョン"

#: ../../client/solo/utils.py:439 ../../client/solo/utils.py:446
msgid "revision"
msgstr "探す"

#: ../../client/solo/utils.py:449
msgid "Slot"
msgstr "スロット"

#: ../../client/solo/utils.py:470
msgid "Size"
msgstr "サイズ"

#: ../../client/solo/utils.py:472 ../../client/solo/commands/ugc.py:382
msgid "Download"
msgstr "ダウンロード"

#: ../../client/solo/utils.py:474
msgid "Checksum"
msgstr "チェックサム"

#: ../../client/solo/utils.py:482
msgid "SHA1"
msgstr "SHA1"

#: ../../client/solo/utils.py:484
msgid "SHA256"
msgstr "SHA256"

#: ../../client/solo/utils.py:490 ../../client/solo/commands/status.py:133
msgid "GPG"
msgstr "GPG"

#: ../../client/solo/utils.py:495
msgid "Dependencies"
msgstr "依存関係"

#: ../../client/solo/utils.py:503 ../../client/solo/utils.py:682
msgid "Legend"
msgstr "凡例"

#: ../../client/solo/utils.py:510
msgid "Conflicts"
msgstr "競合"

#: ../../client/solo/utils.py:515
msgid "Homepage"
msgstr "ホームページ"

#: ../../client/solo/utils.py:525 ../../client/solo/commands/security.py:231
#: ../../client/solo/commands/ugc.py:627
msgid "Description"
msgstr "記載なし"

#: ../../client/solo/utils.py:534
msgid "USE flags"
msgstr "フラグを使用"

#: ../../client/solo/utils.py:550
msgid "CHOST"
msgstr "CHOST"

#: ../../client/solo/utils.py:552
msgid "CFLAGS"
msgstr "CFLAGS"

#: ../../client/solo/utils.py:554
msgid "CXXFLAGS"
msgstr "CXXFLAGS"

#: ../../client/solo/utils.py:558
msgid "Sources"
msgstr "ソース"

#: ../../client/solo/utils.py:563
msgid "Entry API"
msgstr "エントリーのAPI"

#: ../../client/solo/utils.py:565
msgid "Compiled with"
msgstr "コンパイル"

#: ../../client/solo/utils.py:570 ../../client/solo/commands/search.py:180
#: ../../client/solo/commands/ugc.py:375 ../../client/solo/commands/ugc.py:634
#: ../../client/solo/commands/match.py:236
msgid "Keywords"
msgstr "キーワード"

#: ../../client/solo/utils.py:585
msgid "Created"
msgstr "作成"

#: ../../client/solo/utils.py:592 ../../client/solo/commands/_manage.py:786
msgid "License"
msgstr "認可"

#: ../../client/solo/utils.py:614
msgid "Reverse graphing installed package"
msgstr "探す"

#: ../../client/solo/utils.py:626 ../../client/solo/utils.py:785
#: ../../client/solo/commands/config.py:119
#: ../../client/solo/commands/remove.py:323
#: ../../client/solo/commands/source.py:164
#: ../../client/solo/commands/download.py:164
#: ../../client/solo/commands/mask.py:118
msgid "No packages found"
msgstr "見つかりませんでした"

#: ../../client/solo/utils.py:685
msgid "packages passed as arguments"
msgstr "引数として渡されたパッケージ"

#: ../../client/solo/utils.py:688
msgid "packages with no further dependencies"
msgstr "実行時の依存関係"

#: ../../client/solo/utils.py:691
msgid "packages with further dependencies (node)"
msgstr "実行時の依存関係"

#: ../../client/solo/utils.py:694
msgid "packages already pulled in as dependency in upper levels (circularity)"
msgstr "上位レベル (循環) の依存関係として既に引込まパッケージ"

#: ../../client/solo/utils.py:773
msgid "Graphing"
msgstr "グラフ作成"

#: ../../client/solo/main.py:40
msgid "Installed packages repository corrupted. Please re-generate it"
msgstr ""

#: ../../client/solo/main.py:50
msgid "Cannot continue"
msgstr "続行できません"

#: ../../client/solo/main.py:79
msgid "Your hard drive is full! Your fault!"
msgstr ""

#: ../../client/solo/main.py:88
msgid "No more memory dude! Your fault!"
msgstr ""

#: ../../client/solo/main.py:94
msgid ""
"Hi. My name is Bug Reporter. I am sorry to inform you that the program "
"crashed. Well, you know, shit happens."
msgstr ""

#: ../../client/solo/main.py:100
msgid ""
"But there's something you could do to help me to be a better application."
msgstr ""

#: ../../client/solo/main.py:106
msgid "-- BUT, DO NOT SUBMIT THE SAME REPORT MORE THAN ONCE --"
msgstr ""

#: ../../client/solo/main.py:111
msgid "Now I am showing you what happened. Don't panic, I'm here to help you."
msgstr ""

#: ../../client/solo/main.py:148
msgid ""
"Oh well, I cannot even write to TMPDIR. So, please copy the error and mail "
"lxnay@sabayon.org."
msgstr ""

#: ../../client/solo/main.py:163
msgid ""
"Erm... Can I send the error, along with some other information\n"
"about your hardware to my creators so they can fix me? (Your IP will be logged)"
msgstr ""

#: ../../client/solo/main.py:170
msgid "Ok, ok ok ok... Sorry!"
msgstr "申し訳ありませんが... OK OK OK、OK！"

#: ../../client/solo/main.py:176
msgid ""
"If you want to be contacted back (and actively supported), also answer the "
"questions below:"
msgstr "あなたが戻って連絡をしたい場合は、（積極的にサポートされている）また、以下の質問に答えてください。 "

#: ../../client/solo/main.py:183
msgid "Your Full name:"
msgstr "氏名："

#: ../../client/solo/main.py:184
msgid "Your E-Mail address:"
msgstr "あなたのメールアドレス："

#: ../../client/solo/main.py:185
msgid "What you were doing:"
msgstr "あなたは何をしていました。"

#: ../../client/solo/main.py:207
msgid ""
"Thank you very much. The error has been reported and hopefully, the problem "
"will be solved as soon as possible."
msgstr "どうもありがとうございました。エラーが報告されており、うまくいけば、問題ができるだけ早く解決されます。"

#: ../../client/solo/main.py:213
msgid ""
"Ugh. Cannot send the report. Please mail the file below to "
"lxnay@sabayon.org."
msgstr "うーん。レポートを送信することはできません。lxnay@sabayon.orgするには、以下のファイルを郵送してください。"

#: ../../client/solo/main.py:233
msgid "Entropy/Equo version mismatch"
msgstr "エントロピー/ EQUOバージョンの不一致"

#: ../../client/solo/main.py:234
msgid "it could make your system explode!"
msgstr "それはあなたのシステムが爆発することができます！"

#: ../../client/solo/main.py:243
msgid "Entropy is running off a Live System"
msgstr "エントロピーはライブシステムをオフに実行されている"

#: ../../client/solo/main.py:245
msgid "Performance and stability could get severely compromised"
msgstr "パフォーマンスと安定性が著しく損なわれ始める可能性があり"

#: ../../client/solo/main.py:347 ../kernel-switcher:117
msgid "superuser access required"
msgstr "必要なスペース"

#: ../../client/solo/commands/moo.py:113
msgid "moo at user"
msgstr "ユーザーでMOO"

#: ../../client/solo/commands/moo.py:120
msgid "bow to lxnay"
msgstr "lxnayに屈する"

#: ../../client/solo/commands/query.py:72
#: ../../client/solo/commands/query.py:1600
msgid "repository query tools"
msgstr "リポジトリ照会ツール"

#: ../../client/solo/commands/query.py:73
#: ../../client/solo/commands/query.py:154
#: ../../client/solo/commands/cache.py:61
#: ../../client/solo/commands/security.py:69
#: ../../client/solo/commands/conf.py:76 ../../client/solo/commands/ugc.py:72
#: ../../client/solo/commands/ugc.py:105 ../../client/solo/commands/ugc.py:146
#: ../../client/solo/commands/repo.py:68
#: ../../client/solo/commands/rescue.py:74
#: ../../client/solo/commands/pkg.py:73
#: ../../client/solo/commands/preservedlibs.py:68 ../kernel-switcher:49
msgid "available commands"
msgstr "使用可能なコマンド"

#: ../../client/solo/commands/query.py:77
msgid "resolve what package a file belongs to"
msgstr "ファイルが属するものをパッケージに解決"

#: ../../client/solo/commands/query.py:80
#: ../../client/solo/commands/query.py:200
msgid "file path"
msgstr "ファイルパス"

#: ../../client/solo/commands/query.py:87
msgid "show package changelog"
msgstr "パッケージの変更履歴を表示"

#: ../../client/solo/commands/query.py:90
#: ../../client/solo/commands/query.py:100
#: ../../client/solo/commands/query.py:120
#: ../../client/solo/commands/query.py:130
#: ../../client/solo/commands/query.py:215
#: ../../client/solo/commands/query.py:282
#: ../../client/solo/commands/query.py:299
#: ../../client/solo/commands/config.py:57
#: ../../client/solo/commands/remove.py:62
#: ../../client/solo/commands/source.py:56
#: ../../client/solo/commands/install.py:65
#: ../../client/solo/commands/download.py:56
#: ../../client/solo/commands/mask.py:44
msgid "package name"
msgstr "パッケージの名前"

#: ../../client/solo/commands/query.py:97
msgid "show reverse dependencies of package"
msgstr ""

#: ../../client/solo/commands/query.py:107
msgid "search package by description"
msgstr "説明文でパッケージを検索"

#: ../../client/solo/commands/query.py:110
msgid "description keyword"
msgstr ""

#: ../../client/solo/commands/query.py:117
msgid "show files owned by package"
msgstr "パッケージが所有するファイルを表示"

#: ../../client/solo/commands/query.py:127
msgid "search installed packages"
msgstr "インストール済みのパッケージを検索"

#: ../../client/solo/commands/query.py:137
msgid "show packages using the given license"
msgstr "指定されたライセンスを使用しているパッケージを表示"

#: ../../client/solo/commands/query.py:140
msgid "license name"
msgstr "ライセンスの名前"

#: ../../client/solo/commands/query.py:146
#: ../../client/solo/commands/query.py:153
msgid "list packages"
msgstr "パッケージを羅列"

#: ../../client/solo/commands/query.py:157
msgid "list installed packages"
msgstr "インストール済みのパッケージを羅列"

#: ../../client/solo/commands/query.py:160
msgid "only list packages installed by user"
msgstr "ユーザーによってインストールしたパッケージのみ羅列"

#: ../../client/solo/commands/query.py:163
msgid "only list packages installed from given repositories"
msgstr "指定されたレポジトリに含まれるインストール済みパッケージのみ表示"

#: ../../client/solo/commands/query.py:171
msgid "list available packages"
msgstr "利用可能なパッケージを表示"

#: ../../client/solo/commands/query.py:174
msgid "only list packages from given repositories"
msgstr "指定されたレポジトリに含まれるパッケージのみ表示"

#: ../../client/solo/commands/query.py:182
msgid "show packages able to handle the given mimetype"
msgstr "指定されたMIMEタイプを処理可能なパッケージを表示"

#: ../../client/solo/commands/query.py:185
msgid "mimetype"
msgstr "MIMEタイプ"

#: ../../client/solo/commands/query.py:188
#: ../../client/solo/commands/query.py:203
msgid "only show installed packages"
msgstr "インストール済みのパッケージのみ表示"

#: ../../client/solo/commands/query.py:197
msgid "associate file to packages able to handle it"
msgstr ""

#: ../../client/solo/commands/query.py:212
msgid "show runtime libraries needed by the given package"
msgstr "指定されたパッケージに必要なランタイムライブラリを表示"

#: ../../client/solo/commands/query.py:222
msgid "search files not belonging to any packages"
msgstr "どのパッケージにも属さないファイルを検索"

#: ../../client/solo/commands/query.py:228
msgid "show packages requiring the given library name"
msgstr "指定された名前のライブラリを必要とするパッケージを表示"

#: ../../client/solo/commands/query.py:231
msgid "library name (example: libdl.so.2)"
msgstr "ライブラリの名前（例: libdl.so.2）"

#: ../../client/solo/commands/query.py:238
msgid "search package sets"
msgstr "パッケージセットを検索"

#: ../../client/solo/commands/query.py:241
msgid "set name"
msgstr "名前を設定"

#: ../../client/solo/commands/query.py:248
msgid "show packages owning the given slot"
msgstr ""

#: ../../client/solo/commands/query.py:251
msgid "slot name"
msgstr ""

#: ../../client/solo/commands/query.py:258
msgid "show packages owning the given tag"
msgstr "指定されたタグを持つパッケージを表示"

#: ../../client/solo/commands/query.py:261
msgid "tag name"
msgstr ""

#: ../../client/solo/commands/query.py:268
msgid "show packages at the given revision"
msgstr ""

#: ../../client/solo/commands/query.py:271
msgid "revision name"
msgstr ""

#: ../../client/solo/commands/query.py:278
msgid "show the direct dependencies graph for the given package"
msgstr ""

#: ../../client/solo/commands/query.py:285
#: ../../client/solo/commands/query.py:302
msgid ""
"include system packages, build-time dependencies and circular dependencies "
"information"
msgstr "システムパッケージを含む、ビルド時の依存関係と循環依存関係の情報"

#: ../../client/solo/commands/query.py:295
msgid "show the inverse dependencies graph for the given package"
msgstr ""

#: ../../client/solo/commands/query.py:312
msgid "show the number of updates available"
msgstr "利用可能な更新の数を表示する"

#: ../../client/solo/commands/query.py:359
msgid "Belong Search"
msgstr ""

#: ../../client/solo/commands/query.py:408
#: ../../client/solo/commands/query.py:590
#: ../../client/solo/commands/query.py:674
#: ../../client/solo/commands/query.py:782
#: ../../client/solo/commands/query.py:971
#: ../../client/solo/commands/query.py:1344
#: ../../client/solo/commands/query.py:1402
#: ../../client/solo/commands/query.py:1465
#: ../../client/solo/commands/query.py:1513
#: ../../client/solo/commands/search.py:184
#: ../../client/solo/commands/match.py:240
msgid "entry"
msgid_plural "entries"
msgstr[0] ""

#: ../../client/solo/commands/query.py:411
#: ../../client/solo/commands/query.py:577
#: ../../client/solo/commands/query.py:671
#: ../../client/solo/commands/query.py:785
#: ../../client/solo/commands/query.py:974
#: ../../client/solo/commands/query.py:1345
#: ../../client/solo/commands/query.py:1404
#: ../../client/solo/commands/query.py:1467
#: ../../client/solo/commands/query.py:1515
msgid "Keyword"
msgstr "キーワード"

#: ../../client/solo/commands/query.py:415
#: ../../client/solo/commands/query.py:592
#: ../../client/solo/commands/query.py:672
#: ../../client/solo/commands/query.py:717
#: ../../client/solo/commands/query.py:788
#: ../../client/solo/commands/query.py:976
#: ../../client/solo/commands/query.py:1043
#: ../../client/solo/commands/query.py:1292
#: ../../client/solo/commands/query.py:1346
#: ../../client/solo/commands/query.py:1407
#: ../../client/solo/commands/query.py:1470
#: ../../client/solo/commands/query.py:1518
#: ../../client/solo/commands/search.py:182
#: ../../client/solo/commands/match.py:238
msgid "Found"
msgstr "発見"

#: ../../client/solo/commands/query.py:433
msgid "ChangeLog Search"
msgstr "変更履歴検索"

#: ../../client/solo/commands/query.py:443
#: ../../client/solo/commands/query.py:451
#: ../../client/solo/commands/_manage.py:292
msgid "No match for"
msgstr ""

#: ../../client/solo/commands/query.py:479
msgid "No ChangeLog available"
msgstr ""

#: ../../client/solo/commands/query.py:494
msgid "Attention: developer-repo option not enabled"
msgstr ""

#: ../../client/solo/commands/query.py:514
msgid "Reverse Dependencies Search"
msgstr ""

#: ../../client/solo/commands/query.py:579
#: ../../client/solo/commands/libtest.py:201
msgid "Matched"
msgstr ""

#: ../../client/solo/commands/query.py:585
#: ../../client/solo/commands/repo.py:120
msgid "from repository"
msgstr ""

#: ../../client/solo/commands/query.py:587
msgid "from the installed packages repository"
msgstr ""

#: ../../client/solo/commands/query.py:615
msgid "Description Search"
msgstr "説明文検索"

#: ../../client/solo/commands/query.py:639
#: ../../client/solo/commands/query.py:795
#: ../../client/solo/commands/query.py:854
#: ../../client/solo/commands/query.py:985
#: ../../client/solo/commands/query.py:1352
#: ../../client/solo/commands/query.py:1415
#: ../../client/solo/commands/query.py:1478
#: ../../client/solo/commands/query.py:1526
msgid "No matches"
msgstr ""

#: ../../client/solo/commands/query.py:690
msgid "Files Search"
msgstr "ファイル検索"

#: ../../client/solo/commands/query.py:718
msgid "files"
msgstr "ファイル"

#: ../../client/solo/commands/query.py:746
msgid "License Search"
msgstr ""

#: ../../client/solo/commands/query.py:812
msgid "Listing Packages"
msgstr ""

#: ../../client/solo/commands/query.py:905
msgid "Repository is not available"
msgstr ""

#: ../../client/solo/commands/query.py:935
msgid "Searching Mimetype"
msgstr ""

#: ../../client/solo/commands/query.py:1017
msgid "Needed Libraries Search"
msgstr ""

#: ../../client/solo/commands/query.py:1044
msgid "libraries"
msgstr ""

#: ../../client/solo/commands/query.py:1060
msgid "Orphans Search"
msgstr ""

#: ../../client/solo/commands/query.py:1128
msgid "Analyzing"
msgstr ""

#: ../../client/solo/commands/query.py:1142
msgid "Analyzed directories"
msgstr ""

#: ../../client/solo/commands/query.py:1147
msgid "Masked directories"
msgstr ""

#: ../../client/solo/commands/query.py:1152
msgid "Number of files collected on the filesystem"
msgstr ""

#: ../../client/solo/commands/query.py:1157
msgid "Now searching among installed packages"
msgstr ""

#: ../../client/solo/commands/query.py:1188
msgid "Checking"
msgstr ""

#: ../../client/solo/commands/query.py:1203
msgid "Number of total files"
msgstr ""

#: ../../client/solo/commands/query.py:1209
msgid "Number of matching files"
msgstr ""

#: ../../client/solo/commands/query.py:1216
msgid "Number of orphaned files"
msgstr ""

#: ../../client/solo/commands/query.py:1222
msgid "Writing file to disk"
msgstr ""

#: ../../client/solo/commands/query.py:1252
msgid "Total space wasted"
msgstr ""

#: ../../client/solo/commands/query.py:1270
msgid "Required Packages Search"
msgstr ""

#: ../../client/solo/commands/query.py:1288
msgid "Library"
msgstr ""

#: ../../client/solo/commands/query.py:1312
msgid "Package Set Search"
msgstr "パッケージセット検索"

#: ../../client/solo/commands/query.py:1368
msgid "Slot Search"
msgstr ""

#: ../../client/solo/commands/query.py:1431
msgid "Tag Search"
msgstr ""

#: ../../client/solo/commands/query.py:1494
msgid "Revision Search"
msgstr ""

#: ../../client/solo/commands/query.py:1564
#: ../../magneto/src/magneto/gtk/magneto.glade.h:2
msgid "Available Updates"
msgstr "利用可能な更新"

#: ../../client/solo/commands/query.py:1579
msgid "Packages to update:"
msgstr "更新されるパッケージ"

#: ../../client/solo/commands/query.py:1582
msgid "Packages to remove:"
msgstr "削除されるパッケージ"

#: ../../client/solo/commands/query.py:1586
msgid "Packages already up-to-date:"
msgstr "すでに最新のパッケージ"

#: ../../client/solo/commands/query.py:1589
msgid "Critical updates found:"
msgstr ""

#: ../../client/solo/commands/config.py:63
#: ../../client/solo/commands/security.py:93
#: ../../client/solo/commands/security.py:165
#: ../../client/solo/commands/remove.py:68
#: ../../client/solo/commands/deptest.py:61
#: ../../client/solo/commands/source.py:62
#: ../../client/solo/commands/libtest.py:61
#: ../../client/solo/commands/rescue.py:80
#: ../../client/solo/commands/install.py:71
#: ../../client/solo/commands/upgrade.py:66
#: ../../client/solo/commands/download.py:62
#: ../../client/solo/commands/mask.py:49
msgid "ask before making any changes"
msgstr ""

#: ../../client/solo/commands/config.py:69
#: ../../client/solo/commands/security.py:96
#: ../../client/solo/commands/security.py:168
#: ../../client/solo/commands/remove.py:75
#: ../../client/solo/commands/source.py:69
#: ../../client/solo/commands/rescue.py:88
#: ../../client/solo/commands/install.py:78
#: ../../client/solo/commands/upgrade.py:73
#: ../../client/solo/commands/download.py:69
msgid "show what would be done"
msgstr ""

#: ../../client/solo/commands/config.py:76
#: ../../client/solo/commands/remove.py:82
#: ../../client/solo/commands/search.py:76
#: ../../client/solo/commands/command.py:152
#: ../../client/solo/commands/source.py:76
#: ../../client/solo/commands/match.py:91
#: ../../client/solo/commands/install.py:85
#: ../../client/solo/commands/upgrade.py:80
#: ../../client/solo/commands/download.py:76
msgid "verbose output"
msgstr ""

#: ../../client/solo/commands/config.py:129
#: ../../client/solo/commands/status.py:130
#: ../../client/solo/commands/status.py:137
#: ../../client/solo/commands/status.py:144
#: ../../client/solo/commands/remove.py:234
#: ../../client/solo/commands/install.py:307
#: ../../client/solo/commands/install.py:333
#: ../../client/solo/commands/install.py:419
msgid "Not available"
msgstr "利用できない"

#: ../../client/solo/commands/config.py:133
msgid "installed from"
msgstr ""

#: ../../client/solo/commands/config.py:144
msgid "Packages involved"
msgstr ""

#: ../../client/solo/commands/config.py:151
#: ../../client/solo/commands/install.py:609
msgid "Would you like to continue ?"
msgstr "続行しますか？"

#: ../../client/solo/commands/config.py:171
msgid "configure"
msgstr ""

#: ../../client/solo/commands/config.py:194
msgid "configure installed packages"
msgstr "インストール済みのパッケージを設定"

#: ../../client/solo/commands/status.py:105
msgid "Repository name"
msgstr "リポジトリ名"

#: ../../client/solo/commands/status.py:114
msgid "Revision"
msgstr ""

#: ../../client/solo/commands/status.py:126
msgid "Repository class"
msgstr ""

#: ../../client/solo/commands/status.py:140
msgid "Notice Board"
msgstr ""

#: ../../client/solo/commands/status.py:147
msgid "Path"
msgstr "パス"

#: ../../client/solo/commands/status.py:160
msgid "Package URLs"
msgstr "パッケージのURL"

#: ../../client/solo/commands/status.py:175
msgid "show Repositories status"
msgstr ""

#: ../../client/solo/commands/cache.py:60
msgid "manage cache"
msgstr ""

#: ../../client/solo/commands/cache.py:64
msgid "clean Entropy Library Cache"
msgstr ""

#: ../../client/solo/commands/cache.py:67
msgid "show more details"
msgstr ""

#: ../../client/solo/commands/cache.py:70
msgid "print results in a scriptable way"
msgstr ""

#: ../../client/solo/commands/cache.py:127
msgid "Cleaning Entropy cache, please wait ..."
msgstr ""

#: ../../client/solo/commands/cache.py:134
msgid "Entropy cache cleaned."
msgstr ""

#: ../../client/solo/commands/cache.py:145
msgid "manage Entropy Library Cache"
msgstr ""

#: ../../client/solo/commands/update.py:65
#: ../../client/solo/commands/ugc.py:240
#: ../../client/solo/commands/notice.py:59
msgid "repository"
msgstr "リポジトリ"

#: ../../client/solo/commands/update.py:68
msgid "force update"
msgstr "強制的な更新"

#: ../../client/solo/commands/update.py:104
msgid "You must be either root or in this group:"
msgstr ""

#: ../../client/solo/commands/update.py:124
msgid "Sending the update request to Entropy Services"
msgstr ""

#: ../../client/solo/commands/update.py:125
msgid "Repositories will be updated in background"
msgstr ""

#: ../../client/solo/commands/update.py:134
msgid "app-admin/rigo-daemon not installed. Update not allowed."
msgstr ""

#: ../../client/solo/commands/update.py:201
msgid "Have a nice day"
msgstr "良い一日を"

#: ../../client/solo/commands/update.py:206
msgid "Repositories update not allowed"
msgstr ""

#: ../../client/solo/commands/update.py:231
#: ../../client/solo/commands/hop.py:116
msgid "No repositories specified in"
msgstr ""

#: ../../client/solo/commands/update.py:252
#: ../../client/solo/commands/notice.py:125
msgid "Notice board not available"
msgstr ""

#: ../../client/solo/commands/update.py:273
msgid "Notice board"
msgstr ""

#. title
#: ../../client/solo/commands/update.py:286
#: ../../client/solo/commands/security.py:226
#: ../../client/solo/commands/ugc.py:361 ../../client/solo/commands/ugc.py:620
#: ../../client/solo/commands/notice.py:152
#: ../../client/solo/commands/notice.py:189
msgid "Title"
msgstr ""

#: ../../client/solo/commands/update.py:295
msgid "update repositories"
msgstr "レポジトリを更新"

#: ../../client/solo/commands/security.py:68
#: ../../client/solo/commands/security.py:672
msgid "system security tools"
msgstr ""

#: ../../client/solo/commands/security.py:73
msgid "verify installed files using stored checksums"
msgstr ""

#: ../../client/solo/commands/security.py:77
msgid "name of package to check"
msgstr "チェックするパッケージの名前"

#: ../../client/solo/commands/security.py:80
msgid "consider mtime instead of SHA256 (false positives ahead)"
msgstr ""

#: ../../client/solo/commands/security.py:84
msgid "update hashes and mtime (useful after editing config files)"
msgstr ""

#: ../../client/solo/commands/security.py:88
msgid "reinstall faulty packages"
msgstr ""

#: ../../client/solo/commands/security.py:99
#: ../../client/solo/commands/security.py:171
#: ../../client/solo/commands/install.py:99
#: ../../client/solo/commands/upgrade.py:94
msgid "just download packages"
msgstr "パッケージのダウンロードのみ行う"

#: ../../client/solo/commands/security.py:115
msgid "download the latest Security Advisories"
msgstr ""

#: ../../client/solo/commands/security.py:119
msgid "force download"
msgstr "強制的にダウンロード"

#: ../../client/solo/commands/security.py:128
msgid "list all the available Security Advisories"
msgstr ""

#: ../../client/solo/commands/security.py:134
msgid "list only affected"
msgstr ""

#: ../../client/solo/commands/security.py:137
msgid "list only unaffected"
msgstr ""

#: ../../client/solo/commands/security.py:146
msgid "show information about provided advisories identifiers"
msgstr ""

#: ../../client/solo/commands/security.py:151
msgid "advisory indentifier"
msgstr ""

#: ../../client/solo/commands/security.py:158
msgid "automatically install all the available security updates"
msgstr ""

#: ../../client/solo/commands/security.py:222
msgid "Advisory Identifier"
msgstr ""

#: ../../client/solo/commands/security.py:254
msgid "Background"
msgstr ""

#: ../../client/solo/commands/security.py:261
msgid "Exploitable"
msgstr ""

#: ../../client/solo/commands/security.py:267
msgid "Impact"
msgstr ""

#: ../../client/solo/commands/security.py:274
msgid "Impact type"
msgstr ""

#: ../../client/solo/commands/security.py:279
msgid "Revised"
msgstr ""

#: ../../client/solo/commands/security.py:284
msgid "Announced"
msgstr ""

#: ../../client/solo/commands/security.py:289
msgid "Synopsis"
msgstr ""

#: ../../client/solo/commands/security.py:296
msgid "References"
msgstr ""

#: ../../client/solo/commands/security.py:302
msgid "Upstream bugs"
msgstr ""

#: ../../client/solo/commands/security.py:308
msgid "Affected"
msgstr "反映されました"

#: ../../client/solo/commands/security.py:316
msgid "vulnerable versions"
msgstr ""

#: ../../client/solo/commands/security.py:319
msgid "unaffected versions"
msgstr ""

#: ../../client/solo/commands/security.py:324
msgid "Workaround"
msgstr ""

#: ../../client/solo/commands/security.py:331
msgid "Resolution"
msgstr ""

#: ../../client/solo/commands/security.py:370
msgid "no checksum information"
msgstr ""

#: ../../client/solo/commands/security.py:419
msgid "found altered files"
msgstr ""

#: ../../client/solo/commands/security.py:438
msgid "assimilated new hashes and mtime"
msgstr ""

#: ../../client/solo/commands/security.py:449
msgid "unavailable"
msgstr ""

#: ../../client/solo/commands/security.py:472
msgid "Checking system files"
msgstr ""

#: ../../client/solo/commands/security.py:491
msgid "No altered files found"
msgstr ""

#: ../../client/solo/commands/security.py:517
msgid "Altered files have been found"
msgstr ""

#: ../../client/solo/commands/security.py:521
msgid "Packages have been reinstalled successfully"
msgstr "パッケージは正常に再インストールされました"

#: ../../client/solo/commands/security.py:552
msgid "No advisories available or applicable"
msgstr ""

#: ../../client/solo/commands/security.py:606
msgid "Advisory does not exist"
msgstr ""

#: ../../client/solo/commands/security.py:630
msgid "Calculating security updates"
msgstr ""

#: ../../client/solo/commands/security.py:655
msgid "All the available updates have been already installed"
msgstr ""

#: ../../client/solo/commands/conf.py:75
msgid "manage configuration file updates"
msgstr ""

#: ../../client/solo/commands/conf.py:79
msgid "update configuration files"
msgstr ""

#: ../../client/solo/commands/conf.py:144
msgid "Scanning filesystem"
msgstr ""

#: ../../client/solo/commands/conf.py:150
#: ../../client/solo/commands/conf.py:176
msgid "All fine baby. Nothing to do!"
msgstr "すべての罰金赤ちゃん。何も行いません！"

#: ../../client/solo/commands/conf.py:171
msgid "file"
msgstr ""

#: ../../client/solo/commands/conf.py:187
#: ../../client/solo/commands/conf.py:633
msgid "Type a number"
msgstr ""

#: ../../client/solo/commands/conf.py:217
msgid "Please choose a file to update by typing its identification number."
msgstr "その識別番号を入力して更新するためにファイルを選択してください。"

#: ../../client/solo/commands/conf.py:221
msgid "Other options are:"
msgstr "その他のオプションは次のとおりです:"

#: ../../client/solo/commands/conf.py:225
#: ../../client/solo/commands/notice.py:159
#: ../../magneto/src/magneto/core/interfaces.py:196
msgid "Exit"
msgstr "出口"

#: ../../client/solo/commands/conf.py:230
msgid "Automerge all the files asking you one by one"
msgstr ""

#: ../../client/solo/commands/conf.py:235
msgid "Automerge all the files without questioning"
msgstr ""

#: ../../client/solo/commands/conf.py:240
msgid "Discard all the files asking you one by one"
msgstr ""

#: ../../client/solo/commands/conf.py:245
msgid "Discard all the files without questioning"
msgstr ""

#: ../../client/solo/commands/conf.py:258
msgid "Please choose an action to take for the selected file."
msgstr ""

#: ../../client/solo/commands/conf.py:263
msgid "Come back to the files list"
msgstr ""

#: ../../client/solo/commands/conf.py:268
msgid "Replace original with update"
msgstr ""

#: ../../client/solo/commands/conf.py:273
msgid "Delete update, keeping original as is"
msgstr "更新を削除して、元をそのまま残す"

#: ../../client/solo/commands/conf.py:278
msgid "Edit proposed file and show diffs again"
msgstr ""

#: ../../client/solo/commands/conf.py:283
msgid "Interactively merge original with update"
msgstr ""

#: ../../client/solo/commands/conf.py:288
msgid "Show differences again"
msgstr ""

#: ../../client/solo/commands/conf.py:384
#: ../../client/solo/commands/conf.py:439
msgid "Source file"
msgstr ""

#: ../../client/solo/commands/conf.py:389
#: ../../client/solo/commands/conf.py:444
msgid "Destination file"
msgstr ""

#: ../../client/solo/commands/conf.py:394
msgid "Overwrite ?"
msgstr ""

#: ../../client/solo/commands/conf.py:403
msgid "Cannot merge"
msgstr ""

#: ../../client/solo/commands/conf.py:449
msgid "Discard ?"
msgstr ""

#: ../../client/solo/commands/conf.py:455
#: ../../client/solo/commands/conf.py:590
msgid "Discarding"
msgstr ""

#: ../../client/solo/commands/conf.py:464
msgid "Cannot remove"
msgstr ""

#: ../../client/solo/commands/conf.py:480
msgid "Editing file"
msgstr ""

#: ../../client/solo/commands/conf.py:487
msgid "Edited file"
msgstr ""

#: ../../client/solo/commands/conf.py:489
msgid "showing difference"
msgstr "違いを示す"

#: ../../client/solo/commands/conf.py:497
#: ../../client/solo/commands/conf.py:602
#: ../../client/solo/commands/conf.py:613
msgid "Automerging"
msgstr "自動マージ"

#: ../../client/solo/commands/conf.py:538
msgid "Interactive merge"
msgstr ""

#: ../../client/solo/commands/conf.py:554
msgid "OSError during interactive merge"
msgstr ""

#: ../../client/solo/commands/conf.py:561
msgid "IOError during interactive merge"
msgstr ""

#: ../../client/solo/commands/conf.py:571
msgid "Unable to merge file"
msgstr "ファイルをマージすることができません"

#: ../../client/solo/commands/conf.py:621
msgid "Selected file"
msgstr "選択したファイル"

#: ../../client/solo/commands/conf.py:643
#, python-format
msgid "Replacing %s with %s"
msgstr ""

#: ../../client/solo/commands/conf.py:650
#, python-format
msgid "Cannot merge %s"
msgstr ""

#: ../../client/solo/commands/conf.py:658
#, python-format
msgid "Deleting %s"
msgstr "削除%sの"

#: ../../client/solo/commands/conf.py:664
#, python-format
msgid "Cannot remove %s"
msgstr "削除できません %s"

#: ../../client/solo/commands/conf.py:702
msgid "manage package file updates"
msgstr "パッケージファイルの更新を管理する"

#: ../../client/solo/commands/yell.py:34
msgid "You should run equo --help"
msgstr "あなたが実行する必要があり EQUO--help"

#: ../../client/solo/commands/yell.py:35
msgid "You didn't run equo --help, did you?"
msgstr "あなたがしなかった、EQUO--help実行されませんでした？"

#: ../../client/solo/commands/yell.py:36
msgid "Did you even read equo --help??"
msgstr "あなたもEQUO--help読みました？"

#: ../../client/solo/commands/yell.py:37
msgid "I give up. Run that equo --help !!!!!!!"
msgstr "私はあきらめる。それを実行し EQUO--help!!!!!!!"

#: ../../client/solo/commands/yell.py:38
msgid "OH MY GOD. RUN equo --heeeeeeeeeeeeeelp"
msgstr "なんてこった。RUN EQUO--heeeeeeeeeeeeeelp（ヘルプ）"

#: ../../client/solo/commands/yell.py:39
msgid "Illiteracy is a huge problem in this world"
msgstr "非識字は、この世界では大きな問題である。"

#: ../../client/solo/commands/yell.py:40
msgid "Ok i give up, you are hopeless"
msgstr "さて私はあなたが絶望的である、あきらめる"

#: ../../client/solo/commands/yell.py:41 ../../client/solo/commands/yell.py:42
#: ../../client/solo/commands/yell.py:43 ../../client/solo/commands/yell.py:44
#: ../../client/solo/commands/yell.py:45 ../../client/solo/commands/yell.py:47
msgid "Go to hell."
msgstr "地獄に行く。"

#: ../../client/solo/commands/yell.py:46
msgid "Stop that, you idiot."
msgstr "やめて、あなたはバカ。"

#: ../../client/solo/commands/yell.py:117
msgid "yell at user"
msgstr "ユーザーで叫ぶ"

#: ../../client/solo/commands/remove.py:89
#: ../../client/solo/commands/source.py:90
#: ../../client/solo/commands/install.py:111
#: ../../client/solo/commands/upgrade.py:106
#: ../../client/solo/commands/download.py:89
msgid "exclude package dependencies"
msgstr "パッケージの依存関係を除外"

#: ../../client/solo/commands/remove.py:95
#: ../../client/solo/commands/source.py:103
#: ../../client/solo/commands/install.py:124
#: ../../client/solo/commands/upgrade.py:112
#: ../../client/solo/commands/download.py:102
msgid "do not calculate dependencies recursively"
msgstr "再帰的に依存関係を計算していない"

#: ../../client/solo/commands/remove.py:101
#: ../../client/solo/commands/source.py:109
#: ../../client/solo/commands/install.py:130
#: ../../client/solo/commands/upgrade.py:118
#: ../../client/solo/commands/download.py:108
msgid "include dependencies no longer needed"
msgstr "依存関係は不要になったなどが"

#: ../../client/solo/commands/remove.py:107
#: ../../client/solo/commands/install.py:136
#: ../../client/solo/commands/upgrade.py:124
msgid "when used with --deep, include virtual packages"
msgstr "「--deep,」で使用した場合、仮想パッケージを含める"

#: ../../client/solo/commands/remove.py:113
#: ../../client/solo/commands/install.py:142
#: ../../client/solo/commands/upgrade.py:137
msgid "remove package configuration files no longer needed"
msgstr "不要になったパッケージの設定ファイルを削除しない"

#: ../../client/solo/commands/remove.py:119
msgid "force system packages removal (dangerous!)"
msgstr "力システムパッケージの削除（危ない！）"

#: ../../client/solo/commands/remove.py:187
msgid "removal"
msgstr "除去"

#: ../../client/solo/commands/remove.py:204
#: ../../client/solo/commands/source.py:182
#: ../../client/solo/commands/download.py:182
msgid "All done"
msgstr "すべて完了"

#: ../../client/solo/commands/remove.py:216
msgid "These are the packages that should be MANUALLY removed"
msgstr "これらは手動で削除する必要がありますパッケージです"

#: ../../client/solo/commands/remove.py:222
#: ../../client/solo/commands/install.py:399
msgid "These are the packages that would be removed"
msgstr "削除されるパッケージがあります"

#: ../../client/solo/commands/remove.py:263
msgid "Packages that would be removed"
msgstr "削除されるパッケージ"

#: ../../client/solo/commands/remove.py:293
#: ../../client/solo/commands/install.py:490
msgid "Freed disk space"
msgstr ""

#: ../../client/solo/commands/remove.py:300
msgid "Total bandwidth wasted"
msgstr ""

#: ../../client/solo/commands/remove.py:342
msgid "Ouch!"
msgstr "痛い！"

#: ../../client/solo/commands/remove.py:343
msgid "the following system packages were pulled in"
msgstr ""

#: ../../client/solo/commands/remove.py:366
msgid "Would you like to proceed ?"
msgstr ""

#: ../../client/solo/commands/remove.py:381
msgid "remove packages from system"
msgstr "システムからパッケージを削除"

#: ../../client/solo/commands/search.py:68
msgid "search keyword"
msgstr ""

#: ../../client/solo/commands/search.py:72
#: ../../client/solo/commands/repo.py:133
#: ../../client/solo/commands/match.py:87
msgid "quiet output, for scripting purposes"
msgstr ""

#: ../../client/solo/commands/search.py:81
msgid "search among installed packages only"
msgstr "インストール済みのパッケージの中からのみ検索"

#: ../../client/solo/commands/search.py:85
msgid "search among available packages only"
msgstr "利用可能なパッケージの中からのみ検索"

#: ../../client/solo/commands/search.py:169
msgid "Searching"
msgstr ""

#: ../../client/solo/commands/search.py:213
msgid "search packages in repositories"
msgstr "レポジトリ上のパッケージを検索"

#: ../../client/solo/commands/deptest.py:64
#: ../../client/solo/commands/libtest.py:67
#: ../../client/solo/commands/unused.py:68
msgid "show less details (useful for scripting)"
msgstr ""

#: ../../client/solo/commands/deptest.py:67
#: ../../client/solo/commands/libtest.py:74 ../kernel-switcher:45
msgid "just show what would be done"
msgstr "ちょうど行われるであろうものを示して"

#: ../../client/solo/commands/deptest.py:160
msgid "Running dependency test"
msgstr "依存関係のテストを実行する"

#: ../../client/solo/commands/deptest.py:170
msgid "No missing dependencies"
msgstr "ミッシング依存しない"

#: ../../client/solo/commands/deptest.py:175
msgid "These are the dependencies not found"
msgstr "これらが見つからない依存関係である"

#: ../../client/solo/commands/deptest.py:185
msgid "Needed by"
msgstr "が必要とする"

#: ../../client/solo/commands/deptest.py:196
msgid "Would you like to install the packages ?"
msgstr "あなたは、パッケージをインストールしますか？"

#: ../../client/solo/commands/deptest.py:203
#: ../../client/solo/commands/libtest.py:230
msgid "Installing available packages in"
msgstr "で利用可能なパッケージのインストール"

#: ../../client/solo/commands/deptest.py:204
#: ../../client/solo/commands/libtest.py:231
msgid "10 seconds"
msgstr "10秒"

#: ../../client/solo/commands/deptest.py:228
msgid "look for unsatisfied dependencies"
msgstr ""

#: ../../client/solo/commands/command.py:128
msgid "not a valid directory"
msgstr ""

#: ../../client/solo/commands/command.py:143
#: ../../client/solo/commands/pkg.py:80
msgid "not a valid Entropy package file"
msgstr "は有効なエントロピーパッケージファイル"

#: ../../client/solo/commands/command.py:155
#: ../../client/solo/commands/source.py:83
#: ../../client/solo/commands/install.py:92
#: ../../client/solo/commands/upgrade.py:87
#: ../../client/solo/commands/download.py:83
msgid "quiet output"
msgstr ""

#: ../../client/solo/commands/command.py:402
msgid "Acquiring Entropy Resources Lock, please wait..."
msgstr "エントロピーリソースロックを取得しています。お待ちください..."

#: ../../client/solo/commands/command.py:414
msgid "Another Entropy is currently running."
msgstr "もう一つのエントロピーは、現在実行されています。"

#: ../../client/solo/commands/command.py:473
msgid "When you wrote"
msgstr ""

#: ../../client/solo/commands/command.py:475
msgid "You Meant(tm)"
msgstr ""

#: ../../client/solo/commands/command.py:476
msgid "one of these below?"
msgstr ""

#: ../../client/solo/commands/ugc.py:71 ../../client/solo/commands/ugc.py:1011
msgid "manage User Generated Content"
msgstr ""

#: ../../client/solo/commands/ugc.py:75
msgid "login against the given repository"
msgstr ""

#: ../../client/solo/commands/ugc.py:77 ../../client/solo/commands/ugc.py:87
#: ../../client/solo/commands/ugc.py:99 ../../client/solo/commands/ugc.py:140
#: ../../client/solo/commands/repo.py:74 ../../client/solo/commands/repo.py:82
#: ../../client/solo/commands/repo.py:89
#: ../../client/solo/commands/repo.py:112
#: ../../client/solo/commands/repo.py:140
msgid "repository name"
msgstr "リポジトリ名"

#: ../../client/solo/commands/ugc.py:80 ../../client/solo/commands/ugc.py:90
msgid "force action"
msgstr ""

#: ../../client/solo/commands/ugc.py:85
msgid "logout from the given repository"
msgstr ""

#: ../../client/solo/commands/ugc.py:96
msgid ""
"manage package documents in the selected repository (comments, files, "
"videos)"
msgstr ""

#: ../../client/solo/commands/ugc.py:104
msgid "manage Documents"
msgstr ""

#: ../../client/solo/commands/ugc.py:108
msgid "get available documents for the provided package name"
msgstr ""

#: ../../client/solo/commands/ugc.py:111 ../../client/solo/commands/ugc.py:119
#: ../../client/solo/commands/ugc.py:127 ../../client/solo/commands/ugc.py:151
#: ../../client/solo/commands/ugc.py:158
msgid "package name (example: x11-libs/qt)"
msgstr "パッケージの名前（例: x11-libs/qt）"

#: ../../client/solo/commands/ugc.py:116
msgid "add a new document to the provided package name"
msgstr ""

#: ../../client/solo/commands/ugc.py:124
msgid "remove documents from database using their identifiers"
msgstr ""

#: ../../client/solo/commands/ugc.py:130
msgid "document identifier"
msgstr ""

#: ../../client/solo/commands/ugc.py:137
msgid "manage package votes in the selected repository"
msgstr ""

#: ../../client/solo/commands/ugc.py:145
msgid "manage Votes"
msgstr ""

#: ../../client/solo/commands/ugc.py:149
msgid "get vote for the provided package name"
msgstr "提供されるパッケージ名票を取得"

#: ../../client/solo/commands/ugc.py:156
msgid "add vote to the provided package name"
msgstr ""

#: ../../client/solo/commands/ugc.py:200 ../../client/solo/commands/ugc.py:304
msgid "Invalid repository"
msgstr "無効なリポジトリ"

#: ../../client/solo/commands/ugc.py:211 ../../client/solo/commands/ugc.py:315
#: ../../client/solo/commands/ugc.py:439 ../../client/solo/commands/ugc.py:521
#: ../../client/solo/commands/ugc.py:737 ../../client/solo/commands/ugc.py:854
#: ../../client/solo/commands/ugc.py:892
msgid "Repository does not support Entropy Services."
msgstr "リポジトリは、エントロピー·サービスをサポートしていません。"

#: ../../client/solo/commands/ugc.py:221
msgid "Already logged in as"
msgstr ""

#: ../../client/solo/commands/ugc.py:223
msgid "Please logout first"
msgstr ""

#: ../../client/solo/commands/ugc.py:235
msgid "Username"
msgstr "ユーザ名"

#: ../../client/solo/commands/ugc.py:236
msgid "Password"
msgstr "パスワード"

#: ../../client/solo/commands/ugc.py:240
msgid "Please login against"
msgstr "反対にはログインしてください"

#: ../../client/solo/commands/ugc.py:248
msgid "Login aborted. Not logged in."
msgstr "ログインは中止。ログインしていません。"

#: ../../client/solo/commands/ugc.py:262
msgid "Authentication error. Not logged in."
msgstr "認証エラー。ログインしていません。"

#: ../../client/solo/commands/ugc.py:271
msgid "Communication error. Not logged in."
msgstr "通信エラー。ログインしていません。"

#: ../../client/solo/commands/ugc.py:281
msgid "Successfully logged in as"
msgstr "に成功としてログイン"

#: ../../client/solo/commands/ugc.py:288
msgid "From now on, any UGC action will be committed as this user"
msgstr "これからは、どんなUGCアクションは、このユーザーとしてコミットされます"

#: ../../client/solo/commands/ugc.py:325
msgid "Not logged in."
msgstr ""

#: ../../client/solo/commands/ugc.py:334
msgid "User"
msgstr ""

#: ../../client/solo/commands/ugc.py:336
msgid "has been logged out."
msgstr ""

#: ../../client/solo/commands/ugc.py:345
msgid "No title"
msgstr ""

#: ../../client/solo/commands/ugc.py:372
#: ../../client/solo/commands/notice.py:195
msgid "Content"
msgstr ""

#: ../../client/solo/commands/ugc.py:389
msgid "no votes"
msgstr "全く投票しない"

#: ../../client/solo/commands/ugc.py:395
msgid "current package vote"
msgstr "現在のパッケージの投票"

#: ../../client/solo/commands/ugc.py:456 ../../client/solo/commands/ugc.py:466
#: ../../client/solo/commands/ugc.py:483 ../../client/solo/commands/ugc.py:702
#: ../../client/solo/commands/ugc.py:773 ../../client/solo/commands/ugc.py:798
#: ../../client/solo/commands/ugc.py:810 ../../client/solo/commands/ugc.py:822
#: ../../client/solo/commands/ugc.py:867 ../../client/solo/commands/ugc.py:945
#: ../../client/solo/commands/ugc.py:980 ../../client/solo/commands/ugc.py:991
msgid "UGC error"
msgstr "UGCエラー"

#: ../../client/solo/commands/ugc.py:495
msgid "Number of downloads"
msgstr "ダウンロード数"

#: ../../client/solo/commands/ugc.py:502
msgid "No User Generated Content available."
msgstr "いいえユーザーは、コンテンツが利用可能に生成されません。"

#: ../../client/solo/commands/ugc.py:533 ../../client/solo/commands/ugc.py:904
msgid "Not logged in, please login first."
msgstr ""

#: ../../client/solo/commands/ugc.py:543
msgid "Add document"
msgstr ""

#: ../../client/solo/commands/ugc.py:548
msgid "text comment"
msgstr ""

#: ../../client/solo/commands/ugc.py:549
msgid "icon"
msgstr ""

#: ../../client/solo/commands/ugc.py:550
msgid "simple file"
msgstr ""

#: ../../client/solo/commands/ugc.py:551
msgid "simple image"
msgstr ""

#: ../../client/solo/commands/ugc.py:552
msgid "video"
msgstr "ビデオ"

#: ../../client/solo/commands/ugc.py:569
msgid "Insert document title"
msgstr ""

#: ../../client/solo/commands/ugc.py:571
msgid "Insert document description/comment"
msgstr ""

#: ../../client/solo/commands/ugc.py:574
msgid "Insert document's keywords (space separated)"
msgstr ""

#: ../../client/solo/commands/ugc.py:576
msgid "Choose document type"
msgstr ""

#: ../../client/solo/commands/ugc.py:581 ../../client/solo/commands/ugc.py:601
msgid "Entropy UGC document submission"
msgstr ""

#: ../../client/solo/commands/ugc.py:598
msgid "Insert document path"
msgstr ""

#: ../../client/solo/commands/ugc.py:614 ../../client/solo/commands/ugc.py:754
#: ../../client/solo/commands/ugc.py:957
msgid "Please review your submission"
msgstr ""

#: ../../client/solo/commands/ugc.py:642
msgid "Document path"
msgstr "ドキュメントのパス"

#: ../../client/solo/commands/ugc.py:649
msgid "Document type"
msgstr ""

#: ../../client/solo/commands/ugc.py:655 ../../client/solo/commands/ugc.py:969
msgid "Do you want to submit?"
msgstr "送信しますか"

#: ../../client/solo/commands/ugc.py:687
msgid "Invalid document"
msgstr ""

#: ../../client/solo/commands/ugc.py:716
msgid "Document added, thank you!"
msgstr ""

#: ../../client/solo/commands/ugc.py:747
msgid "Documents removal"
msgstr ""

#: ../../client/solo/commands/ugc.py:760
msgid "Document identifiers"
msgstr ""

#: ../../client/solo/commands/ugc.py:765
msgid "Would you like to review them?"
msgstr ""

#: ../../client/solo/commands/ugc.py:788
msgid "Would you like to continue with the removal?"
msgstr ""

#: ../../client/solo/commands/ugc.py:811
msgid "cannot get the requested Document"
msgstr ""

#: ../../client/solo/commands/ugc.py:831
msgid "UGC status"
msgstr ""

#: ../../client/solo/commands/ugc.py:832
msgid "removed successfully"
msgstr ""

#: ../../client/solo/commands/ugc.py:913
msgid "add vote"
msgstr ""

#: ../../client/solo/commands/ugc.py:921
msgid "Insert your vote (from 1 to 5)"
msgstr ""

#: ../../client/solo/commands/ugc.py:925
msgid "Entropy UGC vote submission"
msgstr ""

#: ../../client/solo/commands/ugc.py:946
msgid "invalid vote, must be in range"
msgstr ""

#: ../../client/solo/commands/ugc.py:963
msgid "Vote"
msgstr ""

#: ../../client/solo/commands/ugc.py:992
msgid "already voted"
msgstr ""

#: ../../client/solo/commands/ugc.py:1000
msgid "vote added, thank you!"
msgstr ""

#: ../../client/solo/commands/repo.py:67
#: ../../client/solo/commands/repo.py:737
msgid "manage repositories"
msgstr "レポジトリを管理する"

#: ../../client/solo/commands/repo.py:71
msgid "enable repositories"
msgstr ""

#: ../../client/solo/commands/repo.py:79
msgid "disable repositories"
msgstr ""

#: ../../client/solo/commands/repo.py:87
msgid "add a repository"
msgstr ""

#: ../../client/solo/commands/repo.py:92
msgid "repository description"
msgstr ""

#: ../../client/solo/commands/repo.py:96
msgid "repository database URL"
msgstr ""

#: ../../client/solo/commands/repo.py:100
msgid "repository packages URL"
msgstr "レポジトリ上のパッケージのURL"

#: ../../client/solo/commands/repo.py:104
msgid "repository compression format"
msgstr ""

#: ../../client/solo/commands/repo.py:109
msgid "remove a repository"
msgstr ""

#: ../../client/solo/commands/repo.py:117
msgid "rename a repository"
msgstr "リポジトリの名前を変更"

#: ../../client/solo/commands/repo.py:123
msgid "to repository"
msgstr "リポジトリへの"

#: ../../client/solo/commands/repo.py:128
msgid "list active repositories"
msgstr ""

#: ../../client/solo/commands/repo.py:137
msgid "reorder mirrors basing on response time"
msgstr ""

#: ../../client/solo/commands/repo.py:143
msgid "simulate execution"
msgstr ""

#: ../../client/solo/commands/repo.py:148
msgid "merge content of source repository to destination"
msgstr ""

#: ../../client/solo/commands/repo.py:150
msgid "source repository"
msgstr ""

#: ../../client/solo/commands/repo.py:152
msgid "destination repository"
msgstr ""

#: ../../client/solo/commands/repo.py:156
msgid "also remove dependency conflicts during merge"
msgstr ""

#: ../../client/solo/commands/repo.py:252
msgid "repository already enabled"
msgstr ""

#: ../../client/solo/commands/repo.py:261
#: ../../client/solo/commands/repo.py:315
#: ../../client/solo/commands/repo.py:600
msgid "repository not available"
msgstr ""

#: ../../client/solo/commands/repo.py:281
msgid "repository enabled"
msgstr ""

#: ../../client/solo/commands/repo.py:287
msgid "cannot enable repository"
msgstr ""

#: ../../client/solo/commands/repo.py:306
msgid "repository already disabled"
msgstr ""

#: ../../client/solo/commands/repo.py:337
#: ../../client/solo/commands/repo.py:351
msgid "cannot disable repository"
msgstr ""

#: ../../client/solo/commands/repo.py:345
msgid "repository disabled"
msgstr ""

#: ../../client/solo/commands/repo.py:373
msgid "Repository id:"
msgstr ""

#: ../../client/solo/commands/repo.py:376
msgid "Description:"
msgstr ""

#: ../../client/solo/commands/repo.py:379
msgid "Repository format:"
msgstr ""

#: ../../client/solo/commands/repo.py:383
msgid "Packages URL:"
msgstr "パッケージのURL:"

#: ../../client/solo/commands/repo.py:385
msgid "Repository URL:"
msgstr ""

#: ../../client/solo/commands/repo.py:407
#: ../../client/solo/commands/repo.py:533
msgid "repository added succesfully"
msgstr ""

#: ../../client/solo/commands/repo.py:412
#: ../../client/solo/commands/repo.py:543
msgid "cannot add repository"
msgstr ""

#: ../../client/solo/commands/repo.py:434
#: ../../client/solo/commands/repo.py:483
msgid "repository id not available"
msgstr ""

#: ../../client/solo/commands/repo.py:454
msgid "repository removed succesfully"
msgstr ""

#: ../../client/solo/commands/repo.py:460
msgid "cannot remove repository"
msgstr ""

#: ../../client/solo/commands/repo.py:491
msgid "repository id already available"
msgstr ""

#: ../../client/solo/commands/repo.py:499
msgid "repository id is invalid"
msgstr ""

#: ../../client/solo/commands/repo.py:614
msgid "mirror order:"
msgstr ""

#: ../../client/solo/commands/repo.py:624
msgid "mirrors sorted successfully"
msgstr ""

#: ../../client/solo/commands/repo.py:643
#: ../../client/solo/commands/repo.py:650
msgid "repository not found"
msgstr ""

#: ../../client/solo/commands/repo.py:659
msgid "repository cannot be source and destination"
msgstr ""

#: ../../client/solo/commands/repo.py:667
msgid "merging repositories"
msgstr ""

#: ../../client/solo/commands/repo.py:683
msgid "working on repository"
msgstr ""

#: ../../client/solo/commands/repo.py:700
msgid "merging package"
msgstr ""

#: ../../client/solo/commands/repo.py:724
msgid "done merging packages"
msgstr ""

#: ../../client/solo/commands/source.py:96
#: ../../client/solo/commands/install.py:117
#: ../../client/solo/commands/download.py:95
msgid "only include dependencies of selected packages"
msgstr "選択されたパッケージの依存関係のみ含める"

#: ../../client/solo/commands/source.py:115
#: ../../client/solo/commands/download.py:114
msgid "calculate dependencies relaxing constraints"
msgstr ""

#: ../../client/solo/commands/source.py:121
#: ../../client/solo/commands/install.py:105
#: ../../client/solo/commands/upgrade.py:100
#: ../../client/solo/commands/download.py:120
msgid "include build-time dependencies"
msgstr ""

#: ../../client/solo/commands/source.py:127
msgid "save files into the current working directory"
msgstr ""

#: ../../client/solo/commands/source.py:176
#: ../../client/solo/commands/rescue.py:655
#: ../../client/solo/commands/install.py:596
#: ../../client/solo/commands/download.py:176
msgid "Nothing to do"
msgstr ""

#: ../../client/solo/commands/source.py:207
msgid "sources download"
msgstr ""

#: ../../client/solo/commands/source.py:230
msgid "download packages source code"
msgstr "パッケージのソースコードをダウンロード"

#: ../../client/solo/commands/libtest.py:80
msgid "print broken files to stdout"
msgstr ""

#: ../../client/solo/commands/libtest.py:85
msgid "dump results to files"
msgstr ""

#: ../../client/solo/commands/libtest.py:142
#: ../../client/solo/commands/libtest.py:176
msgid "System is healthy"
msgstr "システムが健全である"

#: ../../client/solo/commands/libtest.py:182
msgid "Libraries/Executables statistics"
msgstr ""

#: ../../client/solo/commands/libtest.py:188
msgid "Not matched"
msgstr ""

#: ../../client/solo/commands/libtest.py:224
msgid "Would you like to install them ?"
msgstr ""

#: ../../client/solo/commands/libtest.py:252
msgid "look for missing libraries"
msgstr ""

#: ../../client/solo/commands/notice.py:168
msgid "Choose one by typing its identifier"
msgstr ""

#: ../../client/solo/commands/notice.py:200
msgid "Link"
msgstr ""

#: ../../client/solo/commands/notice.py:209
msgid "Press Enter to continue"
msgstr ""

#: ../../client/solo/commands/notice.py:217
msgid "repository notice board reader"
msgstr ""

#: ../../client/solo/commands/_manage.py:94
msgid "Scanning configuration files to update"
msgstr ""

#: ../../client/solo/commands/_manage.py:103
msgid "No configuration files to update."
msgstr ""

#: ../../client/solo/commands/_manage.py:108
#, python-format
msgid "There is %s configuration file needing update"
msgid_plural "There are %s configuration files needing update"
msgstr[0] "更新が必要な設定ファイルが%s個あります"

#: ../../client/solo/commands/_manage.py:116
msgid "Please run"
msgstr ""

#: ../../client/solo/commands/_manage.py:136
#, python-format
msgid "There is %s preserved library on the system"
msgid_plural "There are %s preserved libraries on the system"
msgstr[0] "システム上の %s の保存ライブラリがあります。"

#. every package matching app-foo is masked
#: ../../client/solo/commands/_manage.py:245
msgid "Every package matching"
msgstr "あてはまるすべてのパッケージ"

#: ../../client/solo/commands/_manage.py:247
msgid "is masked"
msgstr ""

#: ../../client/solo/commands/_manage.py:265
msgid "Masking reason"
msgstr ""

#: ../../client/solo/commands/_manage.py:277
msgid "matching"
msgstr ""

#: ../../client/solo/commands/_manage.py:279
msgid "is broken"
msgstr ""

#: ../../client/solo/commands/_manage.py:283
msgid "atom"
msgstr ""

#: ../../client/solo/commands/_manage.py:285
msgid "in"
msgstr ""

#: ../../client/solo/commands/_manage.py:294
msgid "in repositories"
msgstr ""

#: ../../client/solo/commands/_manage.py:307
msgid "Not found"
msgstr "見つかりませんでした"

#: ../../client/solo/commands/_manage.py:316
msgid "package needed by"
msgstr "が必要とするパッケージ"

#: ../../client/solo/commands/_manage.py:322
#: ../../client/solo/commands/_manage.py:796
#: ../../client/solo/commands/install.py:424
msgid "from"
msgstr "から"

#: ../../client/solo/commands/_manage.py:421
msgid "Skipped"
msgstr ""

#: ../../client/solo/commands/_manage.py:453
msgid "is not installed"
msgstr ""

#: ../../client/solo/commands/_manage.py:481
msgid "Calculating dependencies"
msgstr "依存関係を計算します。"

#: ../../client/solo/commands/_manage.py:493
msgid "Dependencies not found"
msgstr ""

#: ../../client/solo/commands/_manage.py:504
msgid "Conflicting packages were pulled in"
msgstr ""

#: ../../client/solo/commands/_manage.py:524
#: ../../client/solo/commands/_manage.py:540
msgid "required by"
msgstr ""

#. Conflicting dependencies could have been
#. specified by user, in which case they were
#. not pulled in by anything.
#: ../../client/solo/commands/_manage.py:528
msgid "(no reverse dependencies)"
msgstr ""

#: ../../client/solo/commands/_manage.py:551
msgid "Please mask conflicts using"
msgstr ""

#: ../../client/solo/commands/_manage.py:603
#: ../../client/solo/commands/_manage.py:646
msgid "download"
msgstr "ダウンロード"

#: ../../client/solo/commands/_manage.py:672
msgid "Repositories are old, please run:"
msgstr ""

#: ../../client/solo/commands/_manage.py:696
msgid "Please update the following critical packages"
msgstr ""

#: ../../client/solo/commands/_manage.py:707
msgid "You should install them as soon as possible"
msgstr ""

#: ../../client/solo/commands/_manage.py:728
msgid "Read the license"
msgstr ""

#: ../../client/solo/commands/_manage.py:733
msgid "Accept the license (I've read it)"
msgstr ""

#: ../../client/solo/commands/_manage.py:738
msgid "Accept the license and don't ask anymore (I've read it)"
msgstr ""

#: ../../client/solo/commands/_manage.py:742
msgid "Quit"
msgstr ""

#: ../../client/solo/commands/_manage.py:749
msgid "Your choice (type a number and press enter)"
msgstr ""

#: ../../client/solo/commands/_manage.py:780
msgid "You need to accept the licenses below"
msgstr ""

#: ../../client/solo/commands/_manage.py:788
#: ../../client/solo/commands/preservedlibs.py:142
msgid "needed by"
msgstr ""

#: ../../client/solo/commands/_manage.py:833
msgid "No license data available"
msgstr ""

#: ../../client/solo/commands/_manage.py:844
msgid "No file viewer"
msgstr ""

#: ../../client/solo/commands/_manage.py:845
msgid "License saved into"
msgstr ""

#: ../../client/solo/commands/rescue.py:73
#: ../../client/solo/commands/pkg.py:72 ../../client/solo/commands/pkg.py:461
msgid "execute advanced tasks on packages"
msgstr ""

#: ../../client/solo/commands/rescue.py:93
msgid "check installed packages repository for errors"
msgstr ""

#: ../../client/solo/commands/rescue.py:100
msgid "compact the installed packages repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:106
msgid ""
"re-generate the installed packages repository using the Source Package "
"Manager"
msgstr ""

#: ../../client/solo/commands/rescue.py:113
msgid "re-generate SPM<->Entropy package UIDs mapping"
msgstr ""

#: ../../client/solo/commands/rescue.py:119
msgid ""
"update Entropy installed packages repository merging Source Package Manager "
"changes"
msgstr ""

#: ../../client/solo/commands/rescue.py:130
msgid "create a backup of the installed packages repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:136
msgid "restore a backup of the installed packages repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:179
msgid "Repository error"
msgstr ""

#: ../../client/solo/commands/rescue.py:187
#: ../../client/solo/commands/rescue.py:240
#: ../../client/solo/commands/rescue.py:249
msgid "Sanity Check"
msgstr ""

#: ../../client/solo/commands/rescue.py:188
msgid "installed packages repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:194
msgid "Scanning..."
msgstr "スキャンしています"

#: ../../client/solo/commands/rescue.py:230
msgid "Error checking package"
msgstr ""

#: ../../client/solo/commands/rescue.py:241
msgid "corrupted"
msgstr "破損しています。"

#: ../../client/solo/commands/rescue.py:250
msgid "passed"
msgstr ""

#: ../../client/solo/commands/rescue.py:272
msgid "Compacting the Installed Packages repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:285
msgid "Compaction complete"
msgstr ""

#: ../../client/solo/commands/rescue.py:313
msgid ""
"the Installed Packages repository will be re-generated using the Source "
"Package Manager"
msgstr ""

#: ../../client/solo/commands/rescue.py:324
msgid "I am not joking, this is quite disruptive"
msgstr "私はこれは非常に破壊的である、冗談おりません"

#: ../../client/solo/commands/rescue.py:332
msgid "Understood ?"
msgstr "理解？"

#: ../../client/solo/commands/rescue.py:336
msgid "Really ?"
msgstr ""

#: ../../client/solo/commands/rescue.py:341
msgid "This is your last chance"
msgstr ""

#: ../../client/solo/commands/rescue.py:342
msgid "Ok?"
msgstr ""

#: ../../client/solo/commands/rescue.py:358
#: ../../client/solo/commands/rescue.py:381
msgid "Cannot read metadata"
msgstr ""

#: ../../client/solo/commands/rescue.py:389
msgid "Creating a backup of the current repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:402
msgid "Cannot backup the repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:419
msgid "Cannot delete old repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:429
msgid "Initializing a new repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:452
msgid "Repository creation failed"
msgstr ""

#: ../../client/solo/commands/rescue.py:459
msgid "Repository initialized, generating metadata"
msgstr ""

#: ../../client/solo/commands/rescue.py:489
#: ../../client/solo/commands/rescue.py:752
msgid "Invalid package"
msgstr ""

#: ../../client/solo/commands/rescue.py:502
#: ../../client/solo/commands/rescue.py:766
msgid "Metadata generation error"
msgstr ""

#: ../../client/solo/commands/rescue.py:545
msgid "Indexing metadata, please wait..."
msgstr ""

#: ../../client/solo/commands/rescue.py:550
msgid "Repository metadata generation complete"
msgstr ""

#: ../../client/solo/commands/rescue.py:566
msgid "Scanning Source Package Manager repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:580
msgid "Cannot find package"
msgstr ""

#: ../../client/solo/commands/rescue.py:592
msgid "Scanning Entropy repository"
msgstr ""

#: ../../client/solo/commands/rescue.py:662
msgid "These packages were removed"
msgstr ""

#: ../../client/solo/commands/rescue.py:684
#: ../../client/solo/commands/rescue.py:723
msgid "Continue ?"
msgstr "続行しますか？"

#: ../../client/solo/commands/rescue.py:703
msgid "Removal complete"
msgstr ""

#: ../../client/solo/commands/rescue.py:710
msgid "These packages were added"
msgstr ""

#: ../../client/solo/commands/rescue.py:814
msgid "Update complete"
msgstr "更新完了"

#: ../../client/solo/commands/rescue.py:827
msgid "Re-generating packages mapping"
msgstr ""

#: ../../client/solo/commands/rescue.py:835
msgid "Packages mapping re-generated"
msgstr ""

#: ../../client/solo/commands/rescue.py:863
msgid "No backups found"
msgstr ""

#: ../../client/solo/commands/rescue.py:885
msgid "Select the repository to restore"
msgstr ""

#: ../../client/solo/commands/rescue.py:892
msgid "Entropy Installed Packages Repository backups"
msgstr ""

#: ../../client/solo/commands/rescue.py:931
msgid "Cannot read list of user selected packages"
msgstr ""

#: ../../client/solo/commands/rescue.py:972
msgid "tools to rescue the running system"
msgstr ""

#: ../../client/solo/commands/match.py:83
msgid "match keyword"
msgstr ""

#: ../../client/solo/commands/match.py:95
msgid "return only injected packages "
msgstr ""

#: ../../client/solo/commands/match.py:100
msgid "match among installed packages only"
msgstr ""

#: ../../client/solo/commands/match.py:104
msgid "match among available packages only"
msgstr ""

#: ../../client/solo/commands/match.py:108
msgid "return all the matches, not just the best"
msgstr ""

#: ../../client/solo/commands/match.py:113
msgid "return matches found in every repository"
msgstr ""

#: ../../client/solo/commands/match.py:119
msgid "print download URIs (w/--quiet)"
msgstr ""

#: ../../client/solo/commands/match.py:123
msgid "print repository information (w/--quiet)"
msgstr ""

#: ../../client/solo/commands/match.py:127
msgid "print description too (w/--quiet)"
msgstr ""

#: ../../client/solo/commands/match.py:131
msgid "print \":<slot>\" next to package names (w/--quiet)"
msgstr ""

#: ../../client/solo/commands/match.py:225
msgid "Matching"
msgstr ""

#: ../../client/solo/commands/match.py:273
msgid "match packages in repositories"
msgstr ""

#: ../../client/solo/commands/install.py:148
#: ../../client/solo/commands/upgrade.py:143
msgid "relax dependencies constraints during calculation"
msgstr ""

#: ../../client/solo/commands/install.py:155
#: ../../client/solo/commands/upgrade.py:150
#: ../../client/solo/commands/download.py:127
msgid "download multiple packages in parallel (max 10)"
msgstr ""

#: ../../client/solo/commands/install.py:252
msgid "These are the packages that would be installed"
msgstr ""

#: ../../client/solo/commands/install.py:400
msgid "conflicting/substituted"
msgstr ""

#: ../../client/solo/commands/install.py:435
msgid "Packages needing to be installed/updated/downgraded"
msgstr ""

#: ../../client/solo/commands/install.py:440
msgid "Packages needing to be removed"
msgstr ""

#: ../../client/solo/commands/install.py:447
msgid "Packages needing to be installed"
msgstr ""

#: ../../client/solo/commands/install.py:454
msgid "Packages needing to be reinstalled"
msgstr ""

#: ../../client/solo/commands/install.py:461
msgid "Packages needing to be updated"
msgstr ""

#: ../../client/solo/commands/install.py:468
msgid "Packages needing to be downgraded"
msgstr ""

#: ../../client/solo/commands/install.py:481
msgid "Download size"
msgstr "ダウンロードサイズ"

#: ../../client/solo/commands/install.py:488
msgid "Used disk space"
msgstr ""

#: ../../client/solo/commands/install.py:504
msgid "You need at least"
msgstr ""

#: ../../client/solo/commands/install.py:506
msgid "of free space"
msgstr ""

#: ../../client/solo/commands/install.py:520
msgid "You don't have enough space for the installation. Free some space into"
msgstr ""

#: ../../client/solo/commands/install.py:554
msgid "No package_matches found"
msgstr ""

#: ../../client/solo/commands/install.py:641
msgid "Download complete"
msgstr ""

#: ../../client/solo/commands/install.py:698
msgid "install"
msgstr ""

#: ../../client/solo/commands/install.py:726
msgid "Installation complete"
msgstr ""

#: ../../client/solo/commands/install.py:735
msgid "install or update packages or package files"
msgstr ""

#: ../../client/solo/commands/upgrade.py:130
msgid ""
"remove unmaintained packages, if any. This will respect --ask, --pretend and"
" other switches."
msgstr ""

#: ../../client/solo/commands/upgrade.py:201
msgid "Calculating System Updates"
msgstr "システム更新を計算中"

#: ../../client/solo/commands/upgrade.py:220
msgid "Packages matching update"
msgstr ""

#: ../../client/solo/commands/upgrade.py:226
msgid "Packages matching not available"
msgstr ""

#: ../../client/solo/commands/upgrade.py:232
msgid "Packages matching already up to date"
msgstr ""

#: ../../client/solo/commands/upgrade.py:256
msgid "Nothing to update"
msgstr "更新するものがありません"

#: ../../client/solo/commands/upgrade.py:272
msgid ""
"On the system there are packages that are not available anymore in the "
"online repositories"
msgstr ""

#: ../../client/solo/commands/upgrade.py:277
msgid ""
"Even if they are usually harmless, it is suggested (after proper "
"verification) to remove them."
msgstr ""

#: ../../client/solo/commands/upgrade.py:289
msgid "To automatically remove them, please run: equo upgrade --purge."
msgstr "それらを自動的に削除するには、実行してください： equo upgrade --purge。"

#: ../../client/solo/commands/upgrade.py:300
msgid "Selective"
msgstr ""

#: ../../client/solo/commands/upgrade.py:308
msgid "Would you like to remove them?"
msgstr ""

#: ../../client/solo/commands/upgrade.py:335
msgid "Remove this?"
msgstr ""

#: ../../client/solo/commands/upgrade.py:350
msgid "Nothing to remove"
msgstr ""

#: ../../client/solo/commands/upgrade.py:380
msgid "There are more updates to install, reloading Entropy"
msgstr ""

#: ../../client/solo/commands/upgrade.py:400
msgid "upgrade the system"
msgstr ""

#: ../../client/solo/commands/pkg.py:87
msgid "generate packages from the installed system"
msgstr ""

#: ../../client/solo/commands/pkg.py:91
msgid "installed package name"
msgstr ""

#: ../../client/solo/commands/pkg.py:96 ../../client/solo/commands/pkg.py:112
#: ../../client/solo/commands/pkg.py:128 ../../client/solo/commands/pkg.py:144
msgid "destination directory where to save generated packages"
msgstr ""

#: ../../client/solo/commands/pkg.py:102
msgid "transform SPM package files into Entropy ones"
msgstr ""

#: ../../client/solo/commands/pkg.py:107
msgid "SPM package file path"
msgstr ""

#: ../../client/solo/commands/pkg.py:118
msgid "transform Entropy package files into SPM ones"
msgstr ""

#: ../../client/solo/commands/pkg.py:123 ../../client/solo/commands/pkg.py:139
msgid "Entropy package file path"
msgstr ""

#: ../../client/solo/commands/pkg.py:134
msgid "extract Entropy metadata from Entropy packages"
msgstr ""

#: ../../client/solo/commands/pkg.py:220 ../../client/solo/commands/pkg.py:272
#: ../../client/solo/commands/pkg.py:375 ../../client/solo/commands/pkg.py:423
msgid "broken directory path"
msgstr ""

#: ../../client/solo/commands/pkg.py:233
msgid "generating package"
msgstr ""

#: ../../client/solo/commands/pkg.py:243
msgid "package file creation error"
msgstr ""

#: ../../client/solo/commands/pkg.py:251
msgid "package generated"
msgstr ""

#: ../../client/solo/commands/pkg.py:281 ../../client/solo/commands/pkg.py:382
#: ../../client/solo/commands/pkg.py:430
msgid "working on package file"
msgstr ""

#: ../../client/solo/commands/pkg.py:294
msgid "package file extraction complete"
msgstr ""

#: ../../client/solo/commands/pkg.py:343
msgid "package metadata generation complete"
msgstr ""

#: ../../client/solo/commands/pkg.py:354
msgid "package file generated at"
msgstr ""

#: ../../client/solo/commands/pkg.py:394 ../../client/solo/commands/pkg.py:443
msgid "error during metadata extraction"
msgstr ""

#: ../../client/solo/commands/pkg.py:402
msgid "package file generated"
msgstr ""

#: ../../client/solo/commands/pkg.py:451
msgid "metadata file generated"
msgstr ""

#: ../../client/solo/commands/unused.py:74
msgid "sort packages by size"
msgstr ""

#: ../../client/solo/commands/unused.py:79
msgid "consider packages installed with a Source Package Manager to be wanted"
msgstr ""

#: ../../client/solo/commands/unused.py:192
msgid "Running unused packages test"
msgstr ""

#: ../../client/solo/commands/unused.py:226
msgid "show unused packages (pay attention)"
msgstr ""

#: ../../client/solo/commands/cleanup.py:97
msgid "remove downloaded packages and clean temp. directories"
msgstr ""

#: ../../client/solo/commands/download.py:198
msgid "download packages, essentially"
msgstr ""

#: ../../client/solo/commands/help.py:70
msgid "Entropy Command Line Client, Equo"
msgstr ""

#: ../../client/solo/commands/help.py:77
msgid "force colored output"
msgstr ""

#: ../../client/solo/commands/help.py:102 ../kernel-switcher:162
msgid "this help"
msgstr "このヘルプ"

#: ../../client/solo/commands/hop.py:92
msgid "Already on branch"
msgstr ""

#: ../../client/solo/commands/hop.py:133
msgid "Succesfully switched to branch"
msgstr ""

#: ../../client/solo/commands/hop.py:140
msgid "Now run 'equo upgrade' to upgrade your distribution to"
msgstr ""

#: ../../client/solo/commands/hop.py:149
msgid "Unable to switch to branch"
msgstr ""

#: ../../client/solo/commands/hop.py:161
msgid "upgrade the System to a new branch"
msgstr ""

#: ../../client/solo/commands/version.py:59
msgid "show equo version"
msgstr "equoのバージョンを表示"

#: ../../client/solo/commands/mask.py:53
msgid "only show what would be done"
msgstr ""

#: ../../client/solo/commands/mask.py:125
msgid "These are the packages that would be handled"
msgstr ""

#: ../../client/solo/commands/mask.py:160
msgid "Would you like to continue?"
msgstr ""

#: ../../client/solo/commands/mask.py:174
msgid "action not executed"
msgstr ""

#: ../../client/solo/commands/mask.py:222
msgid "mask one or more packages"
msgstr "パッケージをマスクする"

#: ../../client/solo/commands/mask.py:229
msgid "unmask one or more packages"
msgstr "パッケージのマスクを解除する"

#: ../../client/solo/commands/preservedlibs.py:67
msgid "manage preserved libraries"
msgstr "管理、保存、ライブラリ"

#: ../../client/solo/commands/preservedlibs.py:71
msgid "list the currently preserved libraries"
msgstr "現在保存されたライブラリを一覧表示"

#: ../../client/solo/commands/preservedlibs.py:77
msgid "show libraries that could be garbage collected"
msgstr "ガベージコレクションすることができたショーライブラリ"

#: ../../client/solo/commands/preservedlibs.py:128
msgid "No preserved libraries found"
msgstr "見つかりませ保たライブラリません"

#: ../../client/solo/commands/preservedlibs.py:182
msgid "No preserved libraries to garbage collect"
msgstr "ごみのない保存図書館は収集しませ"

#: ../../client/solo/commands/preservedlibs.py:204
msgid "but owned by"
msgstr "しかしによって所有"

#: ../../client/solo/commands/preservedlibs.py:206
msgid "then just unregister the library"
msgstr "そしてちょうどライブラリの登録を解除"

#: ../../client/solo/commands/preservedlibs.py:219
msgid "Tools to manage the preserved libraries on the system"
msgstr "システム上で保存されたライブラリを管理するためのツール"

#: ../../magneto/src/magneto/qt5/interfaces.py:49
msgid "Magneto Entropy Updates Applet"
msgstr "磁気エントロピーアップデートアプレット"

#: ../../magneto/src/magneto/qt5/interfaces.py:209
#: ../../magneto/src/magneto/gtk/interfaces.py:220
msgid "Your system currently has an outdated version of"
msgstr "お使いのシステムは、古いバージョンを持っている"

#: ../../magneto/src/magneto/qt5/interfaces.py:210
#: ../../magneto/src/magneto/gtk/interfaces.py:221
msgid "installed"
msgstr "インストル"

#: ../../magneto/src/magneto/qt5/interfaces.py:211
#: ../../magneto/src/magneto/gtk/interfaces.py:222
msgid "the latest available version is"
msgstr "利用可能な最新バージョンは"

#: ../../magneto/src/magneto/qt5/interfaces.py:213
#: ../../magneto/src/magneto/gtk/interfaces.py:224
msgid ""
"It is recommended that you upgrade to the latest before updating any other "
"packages"
msgstr "これは、他のパッケージをアップデートする前に、最新のものにアップグレードすることをお勧めします"

#: ../../magneto/src/magneto/qt5/components.py:49
msgid "Close"
msgstr "出口"

#: ../../magneto/src/magneto/qt5/components.py:50
msgid "Launch Application Browser"
msgstr "起動アプリケーションブラウザ"

#: ../../magneto/src/magneto/qt5/components.py:60
msgid "Application updates"
msgstr "アプリケーションのアップデート"

#: ../../magneto/src/magneto/gtk/interfaces.py:147
msgid "System Updates"
msgstr "システム更新"

#: ../../magneto/src/magneto/gtk/components.py:52
msgid "Application"
msgstr "アプリケーション"

#: ../../magneto/src/magneto/gtk/components.py:54
msgid "Latest version"
msgstr "最新バージョン"

#: ../../magneto/src/magneto/gtk/components.py:96
msgid "Critical Information"
msgstr "重要情報"

#: ../../magneto/src/magneto/core/interfaces.py:183
msgid "_Disable Notification Applet"
msgstr "_無効にする通知アプレット"

#: ../../magneto/src/magneto/core/interfaces.py:184
msgid "Disable Notification Applet"
msgstr "無効にする通知アプレット"

#: ../../magneto/src/magneto/core/interfaces.py:185
msgid "_Enable Notification Applet"
msgstr "_通知アプレットを有効にする"

#: ../../magneto/src/magneto/core/interfaces.py:186
msgid "Enable Notification Applet"
msgstr "通知アプレットを有効にする"

#: ../../magneto/src/magneto/core/interfaces.py:187
msgid "_Check for updates"
msgstr "_更新プログラムの確認"

#: ../../magneto/src/magneto/core/interfaces.py:188
msgid "Check for updates"
msgstr "更新プログラムの確認"

#: ../../magneto/src/magneto/core/interfaces.py:189
msgid "_Launch Package Manager"
msgstr "_パッケージマネージャを起動します"

#: ../../magneto/src/magneto/core/interfaces.py:190
msgid "Launch Package Manager"
msgstr "パッケージマネージャをロード"

#: ../../magneto/src/magneto/core/interfaces.py:191
msgid "_Packages Website"
msgstr "_パッケージのウェブサイト"

#: ../../magneto/src/magneto/core/interfaces.py:192
msgid "Use Packages web interface"
msgstr "使用しているパッケージのWebインターフェイス"

#: ../../magneto/src/magneto/core/interfaces.py:193
msgid "_Sabayon Linux Website"
msgstr "_ｻﾊﾞﾖﾝのLinuxのウェブサイト"

#: ../../magneto/src/magneto/core/interfaces.py:194
msgid "Launch Sabayon Linux Website"
msgstr "ｻﾊﾞﾖﾝのLinuxのウェブサイトを立ち上げる"

#: ../../magneto/src/magneto/core/interfaces.py:196
msgid "_Exit"
msgstr "_出口"

#: ../../magneto/src/magneto/core/interfaces.py:335
msgid "System restart needed"
msgstr "システムの再起動に必要な"

#: ../../magneto/src/magneto/core/interfaces.py:336
msgid "This system should be restarted at your earliest convenience"
msgstr "このシステムは、できるだけ早い時期に再起動する必要があります"

#: ../../magneto/src/magneto/core/interfaces.py:343
msgid "Cannot monitor Sabayon updates"
msgstr "サバヨンの更新を監視することはできません"

#: ../../magneto/src/magneto/core/interfaces.py:345
msgid "Entropy DBus service not available"
msgstr "利用できないエントロピーDバスサービス"

#: ../../magneto/src/magneto/core/interfaces.py:346
msgid "unable to communicate with the updates service"
msgstr "アップデートサービスと通信することができません"

#: ../../magneto/src/magneto/core/interfaces.py:364
#, python-format
msgid "There is %s update available"
msgid_plural "There are %s updates available"
msgstr[0] "%s があります利用可能な更新"

#: ../../magneto/src/magneto/core/interfaces.py:370
msgid "Sabayon updates available"
msgstr "サバイヨンアップデート利用可能"

#: ../../magneto/src/magneto/core/interfaces.py:371
msgid "Updates are available"
msgstr "更新が利用可能です"

#: ../../magneto/src/magneto/core/interfaces.py:374
msgid "Upgrade now"
msgstr "今すぐアップグレードし"

#. all fine, no updates
#: ../../magneto/src/magneto/core/interfaces.py:378
#: ../../magneto/src/magneto/core/interfaces.py:380
msgid "Your Sabayon is up-to-date"
msgstr "あなたのサバヨンのは最新のです"

#: ../../magneto/src/magneto/core/interfaces.py:381
msgid "No updates available at this time, cool!"
msgstr "この時点で利用可能なアップデートがありません、かっこいい！"

#: ../../magneto/src/magneto/core/interfaces.py:391
msgid "Repositories are being updated"
msgstr "リポジトリは更新されています"

#: ../../magneto/src/magneto/core/interfaces.py:392
msgid "Sabayon repositories status"
msgstr ""

#: ../../magneto/src/magneto/core/interfaces.py:393
msgid "Repositories are being updated automatically"
msgstr "レポジトリは自動的に更新されています"

#. all fine, no updates
#: ../../magneto/src/magneto/core/interfaces.py:401
#: ../../magneto/src/magneto/core/interfaces.py:402
msgid "System upgrade started"
msgstr "システムのアップグレードが開始"

#: ../../magneto/src/magneto/core/interfaces.py:403
msgid "Do not shutdown nor reboot the computer!"
msgstr "シャットダウンしないかを実行したり、コンピュータを再起動してください！"

#: ../../magneto/src/magneto/core/interfaces.py:496
msgid "Updates Notification Applet Disabled"
msgstr "アップデートの通知アプレット無効"

#: ../../magneto/src/magneto/core/interfaces.py:506
msgid "Updates Notification Applet Enabled"
msgstr "アップデート通知アプレットが有効"

#: ../kernel-switcher:28
msgid "Sabayon Kernel Switcher"
msgstr "ｻﾊﾞﾖﾝのカーネルスイッチャー"

#: ../kernel-switcher:35
msgid "quiet mode"
msgstr "クワイエット·モード"

#: ../kernel-switcher:38
msgid "verbose mode"
msgstr "冗長モード"

#: ../kernel-switcher:42
msgid "ask confirmation"
msgstr "確認を求める"

#: ../kernel-switcher:92
msgid "Package does not exist"
msgstr "パッケージが存在しません"

#: ../kernel-switcher:100
msgid "Not a kernel"
msgstr "未カーネル"

#: ../kernel-switcher:110
msgid "Cannot find your currently running kernel."
msgstr "あなたの現在実行中のカーネルを見つけることができません。"

#: ../kernel-switcher:112
msgid "Try without --from-running."
msgstr "--fromランニングなしで試してみてください。"

#: ../kernel-switcher:127
msgid "No kernel packages found"
msgstr "いいえカーネルパッケージが見つかりませんでした"

#: ../kernel-switcher:145
msgid "install a new or just another kernel"
msgstr "新規またはちょうど別のカーネルをインストール"

#: ../kernel-switcher:150
msgid "use 'uname -r' to determine the running kernel"
msgstr "実行中のカーネルを決定するために」は、'uname-r'を使用"

#: ../kernel-switcher:153
msgid "the new kernel package dependency name"
msgstr "新しいカーネルパッケージの依存関係名"

#: ../kernel-switcher:157
msgid "list kernels"
msgstr "リストのカーネル"

#: ../../magneto/src/magneto/gtk/magneto.glade.h:1
msgid "Magneto Application Updates Notifier"
msgstr "磁気アプリケーションの更新通知機能"

#: ../../magneto/src/magneto/gtk/magneto.glade.h:3
msgid "_Load Package Manager"
msgstr "_パッケージマネージャをロード"
